### ISSUE TITLE
Scrollbar shows up bottom of track description on firefox

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#1026]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/472/84574511-292a4080-ada7-11ea-86e7-802c0b22f886.png">

**Comment by sudara** [comment]
@ofsound Would be sweet if you could look into this. It looks like `.edit_links_and_favorite` is `overflow:auto`. Trying to remove that results in a bit of a mess. It's not clear if it's working around something or a historical artifact...

**Comment by ofsound** [comment]
@sudara I'm pretty sure this overflow issue was fixed right after the stitchES launch in the first update after that.

**Comment by sudara** [comment]
Closing.
