### ISSUE TITLE
Accordion tracks sometimes truncated with scrollbars

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#1053]
I tried to clear out cache, thinking there's some old html in there, but it seems to persist. Something to do with the last deploy / seekbars?...

![Screenshot 2020-10-20 - Alter Ego's Music | alonetone 2](https://user-images.githubusercontent.com/472/96598593-52c41d00-12ef-11eb-9271-d44dcd0a7957.jpg)

**Comment by ofsound** [comment]
@sudara This is a layout bug due to Alter Ego not allowing comments. I'm on it!
