### ISSUE TITLE
ActionView::MissingTemplate in comments#create

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#110]
## Exception in alonetone

**ActionView::MissingTemplate** in **comments#create**
Missing template comments/create, application/create with {:locale=&gt;[:en], :formats=&gt;[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip], :variants=&gt;[], :handlers=&gt;[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:
  * &quot;/data/alonetone-rails4/app/views&quot;
  * &quot;/data/alonetone-rails4/greenfield/app/views&quot;

[View on Bugsnag](https://bugsnag.com/alonetone/alonetone/errors/54e779957a87f8b0b2be5d68?event_id=54e779952cb10c924a029899)

## Stacktrace

    vendor/bundle/ruby/2.1.0/gems/actionview-4.1.9/lib/action_view/path_set.rb:46 - find
    vendor/bundle/ruby/2.1.0/gems/actionview-4.1.9/lib/action_view/lookup_context.rb:124 - find
    vendor/bundle/ruby/2.1.0/gems/actionview-4.1.9/lib/action_view/renderer/abstract_renderer.rb:18 - find_template

[View full stacktrace](https://bugsnag.com/alonetone/alonetone/errors/54e779957a87f8b0b2be5d68?event_id=54e779952cb10c924a029899)

**Comment by sudara** [comment]
Should be a 404?

**Comment by wioux** [comment]
This was caused by a spam bot submitting the form -- normal user interaction should never raise this error. Should I fix it nonetheless?

**Comment by sudara** [comment]
Roger. My bone to pic is that it is frequent and 500 is the wrong error.

Maybe should actually be 406 auto-generated by rails and using responds_with?

```If an acceptable format is not identified, the application returns a ‘406 - not acceptable’ status. Otherwise, the default response is to render a template named after the current action and the selected format, e.g. index.html.erb.```

http://apidock.com/rails/ActionController/MimeResponds/respond_with

**Comment by sudara** [comment]
## Resolved error re-occurred in alonetone

**ActionView::MissingTemplate** in **comments#create**
Missing template comments/create, application/create with {:locale=&gt;[:en], :formats=&gt;[:html], :variants=&gt;[], :handlers=&gt;[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:
  * &quot;/data/alonetone-rails4/app/views&quot;
  * &quot;/data/alonetone-rails4/greenfield/app/views&quot;


[View on Bugsnag](https://bugsnag.com/alonetone/alonetone/errors/54e779957a87f8b0b2be5d68?event_id=54ee38ed042827c95502a212)

## Stacktrace

    vendor/bundle/ruby/2.1.0/gems/actionview-4.1.9/lib/action_view/path_set.rb:46 - find
    vendor/bundle/ruby/2.1.0/gems/actionview-4.1.9/lib/action_view/lookup_context.rb:124 - find
    vendor/bundle/ruby/2.1.0/gems/actionview-4.1.9/lib/action_view/renderer/abstract_renderer.rb:18 - find_template

[View full stacktrace](https://bugsnag.com/alonetone/alonetone/errors/54e779957a87f8b0b2be5d68?event_id=54ee38ed042827c95502a212)
