### ISSUE TITLE
ActionView::Template::Error in playlists#show

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#111]
## Exception in alonetone

**ActionView::Template::Error** in **playlists#show**
undefined method &#x60;user&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/alonetone/alonetone/errors/54e77aaa7a87f8b0b2be5f90?event_id=54e77aaae752cd1f3d00be22)

## Stacktrace

    app/helpers/application_helper.rb:85 - link_to_play
    app/views/assets/_asset_layout.html.erb:3 - _app_views_assets__asset_layout_html_erb___654156146__35350198
    app/views/assets/_asset.html.erb:3 - block in _app_views_assets__asset_html_erb__801479228__35316608
    app/views/assets/_asset.html.erb:2 - _app_views_assets__asset_html_erb__801479228__35316608
    app/views/playlists/_playlist.html.erb:2 - block in _app_views_playlists__playlist_html_erb__605959157__34818538
    app/views/playlists/_playlist_layout.erb:54 - block in _app_views_playlists__playlist_layout_erb___414692008__34840668
    app/views/playlists/_playlist_layout.erb:1 - _app_views_playlists__playlist_layout_erb___414692008__34840668
    app/views/playlists/_playlist.html.erb:1 - _app_views_playlists__playlist_html_erb__605959157__34818538
    app/views/playlists/show.html.erb:6 - block (2 levels) in _app_views_playlists_show_html_erb___694236638__34434888
    app/views/playlists/show.html.erb:5 - block in _app_views_playlists_show_html_erb___694236638__34434888
    app/views/playlists/show.html.erb:3 - _app_views_playlists_show_html_erb___694236638__34434888

[View full stacktrace](https://bugsnag.com/alonetone/alonetone/errors/54e77aaa7a87f8b0b2be5f90?event_id=54e77aaae752cd1f3d00be22)

**Comment by wioux** [comment]
Fixed by the stale Track cleanup (as in #112)
