### ISSUE TITLE
stuck on rake setup 

### ISSUE THREAD

**Issue by jlmitch5** [sudara/alonetone#1148]
When running `rake setup`, I get

Mysql2::Error::ConnectionError: Access denied for user 'jmitchel'@'localhost' (using password: NO)

so I did

$ mysql start
$ mysql -u root -h localhost -p

and then

CREATE USER 'jmitchel'@'localhost' IDENTIFIED BY 'NO';
GRANT ALL PRIVILEGES ON * . * TO 'jmitchel'@'localhost';

$ exit

and then tried again.

It seems I can log in using

$ mysql -u jmitchel -h localhost -p

and then typing NO in the password prompt, so I'm not sure why the rake setup is still failing for me.

Side-note that this is not documented in contrib and probably should be

**Comment by jlmitch5** [comment]
Ah so NO != 'NO' 😅 

closing this.  I'll open up a pr to contrib about the step

**Comment by sudara** [comment]
Howdy! Happy to help, you can also

 `using password: NO` just means that no password was supplied to mysql. 

What is often default for localhost mysql setups (and how I have things setup) is to use the root user which takes no password. 

So you’d just want to specify that in the database.yml.

**Comment by sudara** [comment]
Howdy! Nice to see you here!

`using password: NO` just means that no password was supplied to mysql. It's often default for localhost mysql setups (and how I have things setup locally) to use the root user without the password.

This is also the assumption that the database.yml makes (I believe it's still the assumption rails itself makes), so if you want to use a different user, you'll have to edit the database.yml.

You could hop into the discord https://discord.gg/tvQbf7Ra if you run into further issues or want to chat about things.
