### ISSUE TITLE
Forum login attempt resulted in an error page with 2 sub navs

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#1160]
<img width="770" alt="Screen Shot 2022-01-13 at 5 46 28 PM" src="https://user-images.githubusercontent.com/407724/149431895-2b020b0f-fb0c-4f5b-8ddd-4a647ba51c19.png">

Clicking the Log In button from forum.alonetone.com resulted in: 

<img width="1169" alt="Screen Shot 2022-01-13 at 5 41 51 PM" src="https://user-images.githubusercontent.com/407724/149431680-25924ae7-ba83-48dd-8719-ad5963767249.png">

at this URL

<img width="454" alt="IMG_1751" src="https://user-images.githubusercontent.com/407724/149431766-513d4d32-55ca-4dee-bae5-a15cdeb464de.png">

I got the same error clicking this "Sign Up" link as well:

<img width="345" alt="Screen Shot 2022-01-13 at 5 49 54 PM" src="https://user-images.githubusercontent.com/407724/149432222-79f665cd-5e5d-4501-b8f9-2a1998ea2663.png">

**Comment by sudara** [comment]
https://app.bugsnag.com/alonetone/alonetone/errors/61e0c3c30bfcdb00071c98f6?filters[event.since]=all&filters[app.type]=rails&filters[error.status]=new

**Comment by sudara** [comment]
Closed by 393c5e62b44d5c84556098222919680bee889228 with tests
