### ISSUE TITLE
Active track on user page keeps playing on playlist page

### ISSUE THREAD

**Issue by atlesque** [sudara/alonetone#1169]
To reproduce:

- Go to a user's page. The user must have at least one playlist
- Play a track from their page
- While the track is playing, navigate to the playlist page
- Play a track from the playlist
- Both tracks are playing simultaneously

Expected: The first track to stop before playing the second track.

**Comment by sudara** [comment]
Thanks for this! This is probably a bug with the recent turbo refactor.
