### ISSUE TITLE
ArgumentError in comments#index

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#121]
## Exception in alonetone

**ArgumentError** in **comments#index**
invalid value for Integer(): &quot;399999\&quot; and(select 1 from(select count(*),concat((select (select (SELECT distinct concat(0x7e,0x27,&#x27;ololo&#x27;,0x27,0x7e) FROM information_schema.schemata LIMIT 1)) from information_schema.tables limit 0,1),floor(rand(0)*2))x from information_schema.tables group by x)a) and -- \&quot;x\&quot;=\&quot;x&quot;

[View on Bugsnag](https://bugsnag.com/alonetone/alonetone/errors/54e7b8947a87f8b0b2bedb4b?event_id=54e7ba0ada3787845600badd)

## Stacktrace

    app/controllers/comments_controller.rb:46 - index

[View full stacktrace](https://bugsnag.com/alonetone/alonetone/errors/54e7b8947a87f8b0b2bedb4b?event_id=54e7ba0ada3787845600badd)

**Comment by sudara** [comment]
Things like this make me want to prioritize upgrading rails, we need those security patches :)

**Comment by wioux** [comment]
We're upgraded as of today :)
