### ISSUE TITLE
Investigate duplicate track notification emails

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#125]
They seem to send twice, at least for me:

![2015-03-05 inbox](https://cloud.githubusercontent.com/assets/472/6513106/f3298266-c378-11e4-8142-34616e872f90.jpg)

I need to just check if I'm subscribed twice with 2 different accounts or if this is a real issue.

**Comment by wioux** [comment]
You are in fact subscribed from two different accounts. Closing this issue unless there have been other reports of duplicates.
