### ISSUE TITLE
Improve support for tracks being "private"

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#143]
Right now, only moderators/admins can upload private tracks since the feature isn't really built out. We want to continue to build the feature out a bit, so here are some starting places:

* [x] When private tracks are commented on, their comments should not show up on the home page or on `/comments` unless you are a mod/admin.
* ~[ ] We need to add a publish button to the normal track edit page (the mass edit page has one)~

**Comment by sudara** [comment]
Plotly is 800kb gzipped, so the current contender is https://gionkunz.github.io/chartist-js/ despite it being a quiet project.

**Comment by innatewonderer** [comment]
What I don't understand is if a track is private, it doesn't actually show up for other users.. so no comment can be made on the track.

Also, I had to change track's private setting from the console. Can't find a place in the code that actually changes that. Is it in `greenfield` land? I changed that setting as well, but `https://greenfield.dev:3000/innatewonderer/tracks/sunday-morning-music-2016-remaster/edit` can't be found. What am I missing?

**Comment by sudara** [comment]
An admin, a moderator, or the user themselves can comment on the track. 

You are right — the track won't show up for other users – but the comment will show up on the main page of comments, so we still need to force the comment to be private...

But you are right: the only way to make a track public is via the console on the `mass edit` page, which is sorta silly, so we need to fix that up too. I'm fleshing this issue out a bit.

![alonetone 2018-10-11 10-12-35](https://user-images.githubusercontent.com/472/46821674-32474c80-cd3e-11e8-8dcb-a55b5a235d83.jpg)

**Comment by innatewonderer** [comment]
Confirming that we are already only displaying public comments on home page in [assets_controller](https://github.com/sudara/alonetone/blob/master/app/controllers/assets_controller.rb#L295)
```
  def set_related_lastest_variables
    ...
    @comments = admin? ? Comment.last_5_private : Comment.to_other_members.last_5_public
    ...
  end
``` 
We can tighten comments controller a little bit, but it's already allowing comments to `moderator?` mostly.

**Comment by innatewonderer** [comment]
I don't see `Make Private` for tracks even on `/mass_edit` page.  Probably another feature that didn't transfer from old design @sudara ?

![alonetone](https://user-images.githubusercontent.com/2320322/49197873-a2497a80-f35e-11e8-8f5f-b831837df1e4.png)

**Comment by innatewonderer** [comment]
Looks like we already have Publish button on `assets#edit`page. We just have no way currently to make a track private (from what I can see)

![alonetone](https://user-images.githubusercontent.com/2320322/49198447-1e44c200-f361-11e8-9dcc-8d83f7a53923.png)
