### ISSUE TITLE
Fix dupes of Recent Listeners

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#144]
Because of the upgrade to Mysql 5.7, this query stopped working. Need to get uniq/distinct listeners on the single track page.

**Comment by mishraak** [comment]
I was trying to see if I can contribute to this project and hence checking if there were duplicates but for multiple tracks wasn't able to find any duplicates in the 'Recent Listeners'. Has this been fixed already? Am I missing something here?

**Comment by sudara** [comment]
Hey @mishraak 

Thanks for wanting to help out!

I believe it's still an issue https://alonetone.com/gl1tchkids/tracks/psalty-as-fuck-1

This relationship needs to be unique:
https://github.com/sudara/alonetone/blob/master/app/models/asset.rb#L19-L21
