### ISSUE TITLE
Migrate Paperclip to ActiveStorage

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#166]
Migrate paperclip to Active Storage without moving existing file locations in s3.

https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md

**Comment by Manfred** [comment]
- [ ] Run Active Storage migrations to create `active_storage_blobs` and `active_storage_attachments`.
- [ ] Make sure `config/alonetone.yml` is complete and the `secret` is set correctly (must be exactly the same as `secret_key_base` **or things will break**)
- [ ] Run `RAILS_ENV=production bundle exec bin/migrate-storage` (in tmux or screen)

Then we can copy the production database over to a local machine and test if everything was migrated properly. Switch to `mst/replace-paperclip-with-active-storage` locally so it uses the migrated data. This requires the correct `secret` and Amazon configuration from production, but it should be able to run in development mode just fine.

When we've verified that everything works properly, we do the following:

- [ ] Run `RAILS_ENV=production bundle exec bin/migrate-storage` to catch recent uploads
- [ ] Take down Alonetone
- [ ] Run `RAILS_ENV=production bundle exec bin/migrate-storage` to be absolutely sure there are no new uploads
- [ ] Merge `mst/replace-paperclip-with-active-storage` into master and deploy

**Comment by sudara** [comment]
QA:

* [ ] Existing mp3s play
* [ ] Existing image are visible
* [ ] New images are uploaded and variants created successfully
* [ ] New mp3s are uploaded
* [ ] Waveforms created successfully

**Comment by sudara** [comment]
On this random image, the 800x800 is 61kb resized by imagemagick vs. 78kb with 61kb with vips https://alonetone.com/sudara/playlists/continue/continous-playback-test-a-1

<img width="436" alt="image" src="https://user-images.githubusercontent.com/472/57698654-65e0b100-7656-11e9-8548-d76a8df304c4.png">

Interestingly, neither of the resizers caught that the image was 300dpi and resized it down to 72dpi.

**Comment by Manfred** [comment]
For an image that was digitally produced it really doesn't make a lot of sense to specify the DPI. That's an attribute of something that produces an image or presents it. I would be surprised if anything really cares about that metadata.

**Comment by sudara** [comment]
Cloudfront requires a key for an uploaded mp3 https://cdn.alonetone.com/4an3wfnqsn3tl1vtxd8vhcovsl9q

But looks like ACL isn't right for s3, we get a public URL without a key:

https://s3.amazonaws.com/stash.alonetone.com/4an3wfnqsn3tl1vtxd8vhcovsl9q

**Comment by Manfred** [comment]
What controller is doing this?

**Comment by sudara** [comment]
I uploaded a file on the branch (https://github.com/sudara/alonetone/tree/mst/replace-paperclip-with-active-storage) and tested manually to see if i could access it on cloudfront/s3 without a key.

**Comment by Manfred** [comment]
> But looks like ACL isn't right for assets on s3, we get a publicly accessible mp3 without a key: https://s3.amazonaws.com/stash.alonetone.com/4an3wfnqsn3tl1vtxd8vhcovsl9q

I dug into the bucket policy and found that it allows public read for all objects except `/mp3`.

```json
{"Version":"2008-10-17","Id":"stashalonetonepolicy","Statement":[{"Sid":"AllowReadToAllExceptMp3","Effect":"Allow","Principal":{"AWS":"*"},"Action":["s3:GetObject","s3:GetObjectVersion"],"NotResource":["arn:aws:s3:::stash.alonetone.com/mp3/*","arn:aws:s3:::stash.alonetone.com/mp3/"]},{"Sid":"AllowLoggedInToDoAllTheThings","Effect":"Allow","Principal":{"AWS":"arn:aws:iam::341048815538:root"},"Action":"s3:*","Resource":["arn:aws:s3:::stash.alonetone.com/*","arn:aws:s3:::stash.alonetone.com"]},{"Sid":"3","Effect":"Allow","Principal":{"AWS":"arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity EY9AR8CDPZM6E"},"Action":"s3:GetObject","Resource":"arn:aws:s3:::stash.alonetone.com/*"}]}
```

I assume this was done before you started using CloudFront, but that's the reason why objects in the root of the bucket are now public.

**Comment by Manfred** [comment]
Next step towards deploying the Active Storage branch.

- [ ] Run `RAILS_ENV=production bundle exec bin/migrate-storage` to catch recent uploads
- [ ] Add `fastly_base_url: https://fastly.alonetone.com/process` to the production section in `config/alonetone.yml`
- [ ] Take down Alonetone
- [ ] Merge `mst/replace-paperclip-with-active-storage` into master and deploy
- [ ] Run `RAILS_ENV=production bundle exec bin/migrate-storage` to be absolutely sure there are no new uploads

The migration script will no longer generate variants so we shouldn't be charged for bandwidth.
