### ISSUE TITLE
Improve support for marking upload tracks as spam

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#174]
This page currently includes users who only have spam tracks:
https://alonetone.com/users/by/new_artists

Additionally, we display spam tracks as if they are "private" which causes some confusion for users.

So the main goal is to make spam handling for tracks a bit better.

* [ ] Right now, on `update` tracks are marked as "private" which is a misnomer. Instead, let's add a new column called `is_spam` (We can't call it `spam` because `rakismet` adds a `spam?` method which fires the API call). 
* [ ] Instead of happening on update, we should fire off a job which makes the API call to check spam status. There can be 1 job per track, or 1 job for all tracks uploaded (since folks can either upload a zip or multiple files) This is the current code that runs on update: https://github.com/sudara/alonetone/blob/master/app/controllers/assets_controller.rb#L159-L160 — either way, we need some specs that a job was created.
* [ ] We should only update `User#assets_count` after we know the track is not spam, this should have specs.
* [ ] There need to be some changes (with specs) to `AssetsController#spam` and `#unspam`: If a track is manually marked as spam (this can be done from the UI) it should reduce the `assets_count` by 1.  https://github.com/sudara/alonetone/blob/master/app/controllers/assets_controller.rb#L186-L198
* [ ] Right now when tracks go from private to public, we email out to their followers. We want to do the same thing when a track goes from spam to not spam (so false positives don't suffer when unspammed) https://github.com/sudara/alonetone/blob/master/app/models/asset.rb#L117-L123

**Comment by innatewonderer** [comment]
@sudara what makes track a `spam` track? I didn't find anything either in `asset` model or in `track` model that would hint at spam...

**Comment by sudara** [comment]
I think I answered in slack, but right now the column is called `private` — we probably actually want to add an `is_spam` column too and separate it from private tracks (which are available to Users with `greenfield_enabled`, as well as re-evaluate the mysql indexes to add `is_spam` so the whole site doesn't slow down.
