### ISSUE TITLE
Add Track Title to Asset Notification Emails

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#189]
These emails were written before we sent them async — so there was no title or description in them originally. 

<img width="666" alt="image" src="https://user-images.githubusercontent.com/472/44468058-aa3da400-a624-11e8-9a40-aa4391042c3a.png">

Need to confirm (alter/write a spec) that when a title is left to the default, the filename is used.

**Comment by innatewonderer** [comment]
Being addressed here: https://github.com/sudara/alonetone/pull/191
