### ISSUE TITLE
Add instant-unsubscribe "flow" to follow emails 

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#190]
```
You are getting this email because you decided to follow montgomeru. You can change your mind by clicking "un-follow" here:
https://alonetone.com/montgomeru

You can also turn off all emails by editing your profile at alonetone.
```

It's a nicer experience (and less of a spam risk) to update this from a manual "hey, you can turn it off after logging in" to actual links that can be clicked to instantly:

1. unfollow the artist
2. turn notifications off for your followers 

I'm not sure if we need to issue tokens or if that's overkill and we can just create routes. Probably just the latter which means we'd need ensure:

1. If the user isn't logged in, logging in will then properly forward them to the unsubscribe url without any further action. Ideally we have a request spec for this flow.
2. We display a flash notice and in the flash notice include a link to revert the action. This will allow accidents to happen without causing UX burden (people trying to figure out where they need to click).

**Comment by matthewheath** [comment]
Implemented. Closing out.
