### ISSUE TITLE
[Admin] setup `/user` namespace

### ISSUE THREAD

**Issue by innatewonderer** [sudara/alonetone#268]
- [ ] setup `/users` admin section
- [ ] incorporate feedback from [Sudara](https://github.com/sudara/alonetone/pull/254#issuecomment-433312721) to get us started

timestamp | IP | user login | user bio truncated... |  [Mark All Tracks As Spam] | [Add IP to Blocklist] | [ Delete User] 
---|---|---|---|---|---|---|

**Comment by sudara** [comment]
I'm thinking we want a "filter by" element that breaks down user types and provides counts that includes the categories here https://alonetone.com/users but with some more options for admin:

Trackless Unactivated older than 4 months (443)
```
User.where('perishable_token is not null').where('created_at < ?', 4.weeks.ago).where('assets_count = 0')
```

Musicians who reset pass and never clicked (33)
```
User.where('perishable_token is not null').where('assets_count > 0')
```

Trackless never updated (16085)
```
User.where('DATE(created_at) = DATE(updated_at)').where('assets_count = 0')
```

Musicians using bandwidth this month (447)
```
User.order('bandwidth_used desc').where('created_at > ?', 4.weeks.ago).limit(25)
```

Musicians using most bandwidth total (25)
```
User.order('bandwidth_used desc').limit(25)
```
