### ISSUE TITLE
Only show "Other tracks that need your love" on mass_edit when appropriate 

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#301]
The point of "Other tracks you love" is to encourage others to edit track descriptions where they might have forgotten them.

However, we probably should have two changes here so that the partial is only shown when:

1. The user has more than 1 track (so if this is the first upload, don't show it)
2. And those tracks actually are missing descriptions

![white theme remove other tracks that need your love 2018-11-15 18-44-52](https://user-images.githubusercontent.com/472/48571183-8d083100-e906-11e8-938b-d65e192be19a.jpg)

**Comment by innatewonderer** [comment]
I've noticed that we redirect a user to `/tracks/mass_edit?assets%5B%5D=107305` on Asset # Upload and Publish (or Don't publish). Is it intentional to cover cases when multiple records are uploaded at once? (is it even a feature?)

Should we redirect to `assets#edit` instead?
