### ISSUE TITLE
Refactor Alonetone's Heart

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#360]
Work scheduled for Jan 7-18th 2018.

Here are some details and thoughts.

1. Refactor alonetone's paperclip implementation to use ActiveStorage. There are only 2 models, `Pic` and `Asset` (mp3s). We could consider renaming `Asset` to `Mp3` as there is constant confusion on the difference between track (item in a playlist) vs. asset. 
https://github.com/sudara/alonetone/blob/master/config/initializers/paperclip.rb#L2-L18

2. Keep old filenames the same so that s3 objects don't have to move.

3. Account for the ID3 tag logic on upload currently performed here: https://github.com/sudara/alonetone/blob/eae91147db1ffa5175341722387c8280b8a1e194/lib/paperclip_processors/mp3_paperclip_processor.rb

4. Clean up old Pic thumbnail sizes from s3 production (we don't use anything under 200x200, there are probably orphaned pics up there too):  https://github.com/sudara/alonetone/blob/master/app/models/pic.rb#L7-L9

5. Refactor ugly 2008 logic that allows folks to upload 1 file, 1 url, multiple files, or 1 zipfile on upload — maybe stick it in a tested service object https://github.com/sudara/alonetone/blob/52454bf0eab344ab0321168ad4359b9c606762e0/app/controllers/assets_controller.rb#L239-L259

6. Client side: Implement multiple file selection as well as some form of drag n drop uploading + progress indicator. Expose the "upload from a url" UI, keeping into account we need to server side validate and process ID3 tags for mp3s as well as thumbnails for Pics.

7. Add some request/controller level testing around uploads (we are all good on the lower level stuff).

8. We are going to start allowing moderators and eventually paying users to upload zip files (flac/high quality mp3) attached to playlists. This is why `s3_direct_upload` is present. There's only some (crappy) UI in the dark theme for this, search for `s3-uploader`. This feature isn't a priority, however if we have time we can get it in place as well.

Some notes: 

* We currently serve assets in production with cloudfront https://github.com/sudara/alonetone/blob/master/app/concerns/listens.rb#L13

* Happy to run rails master if we want/need to take advantage of work done on active storage there https://github.com/rails/rails/blob/master/activestorage/CHANGELOG.md

* Assets can be marked as spam (via aksimet), private (only moderators can do this, soon to release more widely), and deleted via paranoia (this is being implemented now, see #359)

* Currently emails are triggered to send out to followers on the `mass_edit` page 10 min after upload. This page lets people quickly edit descriptions into all tracks. 

* ID3 tags are used to determine if a playlist should be automatically created on upload to house the tracks, right now it's pretty rudimentary https://github.com/sudara/alonetone/blob/715bed0c4b111e16f1522f34346d73292bb09eb4/app/controllers/assets_controller.rb#L263

* There is an old engine in /greenfield that we are scheduled to remove (it shows up on the listenapp.com domain)

**Comment by Manfred** [comment]
I have some suggestions:

* Rename Track to PlaylistEntry for clarity
* Rename Asset to Track for clarity
* Retire Pic

Then we are left with something like this:

```ruby
class User
  has_many :playlists
  has_many :tracks
  has_one_attached :avatar
end

class Playlist
  belongs_to :user
  has_many :playlist_entries
  has_many :tracks, through: :playlist_entries
  has_one_attached :cover_image
end

class PlaylistEntry
  belongs_to :playlist
  belongs_to :track
end

class Track
  belongs_to :user
  has_many :playlist_entries
  has_one_attached :audio_file
  has_one_attached :waveform_image
end
```

**Comment by sudara** [comment]
:clap::clap::clap:
