### ISSUE TITLE
Thin and sqlite in the Gemfile.

### ISSUE THREAD

**Issue by Manfred** [sudara/alonetone#385]
Can we remove `thin` and `sqlite` from the Gemfile? Maybe replace `thin` with `puma`?

**Comment by sudara** [comment]
I'm not 100% sure but @ofsound might be using sqlite locally (not mysql). Ben, can you check your config/database.yml?

We can remove thin. 

We can also migrate to postgres :D

**Comment by ofsound** [comment]
development:
  adapter: mysql2
  database: alonetone_dev
  username: root
  password: 
  host: localhost
  encoding: utf8
  variables:
    sql_mode: TRADITIONAL
test:
  adapter: mysql2
  database: alonetone_test2
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: 
  username: alonetone_prod
  password: 
  host: localhost
  encoding: utf8
