### ISSUE TITLE
Renaming an existing track doesn't update track title or mp3 href

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#477]

**Comment by Manfred** [comment]
I'll look at this on Monday.

**Comment by Manfred** [comment]
@ofsound where did you find this issue? I tried editing a track on both the white and dark theme and they both work for me. The only slightly weird issue on the dark theme is that it doesn't redirect after saving the track.

**Comment by ofsound** [comment]
If I change the title of one of my tracks, the changes don't appear on my user page listings (or the homepage) for quite a while. The single track view with the new song title and URL works fine.

**Comment by ofsound** [comment]
I renamed this track from "night or day", to "night or day (demo)" and the change shows up on the Latest Listens, but are stuck with the old info on the other stacks of tracks like  Recently Listened To, Latest Music

![night-or-day](https://user-images.githubusercontent.com/407724/54633900-b10b8880-4a46-11e9-8737-1551e3aa5ab5.png)

**Comment by Manfred** [comment]
Ah, so it's a caching issue.

**Comment by Manfred** [comment]
I believe the tradeoff here is between performance and accuracy, it's probably best if @sudara  makes a decision in this case. The drawback is that we would have to update all records related to the asset when it's saved, which is a pretty expensive database operation.

I personally think it's not that bad to have the cache is wrong for a little while, but we might want to change the permalinks to include the resource ID so the links don't break. I Sudara you already did something like this in greenfield: `/petere/tracks/much-like-cheddar` becomes `/petere/tracks/9754-much-like-cheddar` and we attempt to use the ID before falling back to the permalink for now. This would also allow us to remove the permalink column from all records in the future.

**Comment by sudara** [comment]
Hmm,  I think we should be using Rails' collection caching here if possible. I definitely would like to keep the UI up to date, we aren't at a point where we need to make tradeoffs due to performance, the caching is a "nice to have".

**Comment by sudara** [comment]
> we should be using Rails' collection caching here if possible.

Not sure what I was thinking here, there is no caching happen on the group of tracks, just on the individual asset.

> we might want to change the permalinks to include the resource ID

We use the id only on emails for this reason. Using the id for playback reasons here makes sense to me, it will make sure playback doesn't break even if someone loads the page before a rename happens and then presses play. So this would be nice...

But I guess the problem here is this:

```
irb(main):001:0> Asset.last.cache_key
   (0.2ms)  SET  @@SESSION.sql_mode = 'TRADITIONAL',  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
  Asset Load (0.2ms)  SELECT `assets`.* FROM `assets` ORDER BY `assets`.`id` DESC LIMIT 1
=> "assets/108194"
```

(no date in the cache key)
