### ISSUE TITLE
Navigating mobile with dropdown user menu opens target page with that menu stuck open

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#490]

**Comment by sudara** [comment]
Sounds turbolinks-y.

**Comment by sudara** [comment]
Could be solved by adding `initialize()` method here https://github.com/sudara/alonetone/blob/master/app/javascript/controllers/user_dropdown_controller.js that calls `this.slideClosed()` or maybe doing that on `before:visit` with turbolinks. Basically we aren't cleaning up after ourselves there...

**Comment by ofsound** [comment]
I think this had been fixed when an initialize() function was added, but it must not be hitting that code on a new page load after a dropdown menu click.
