### ISSUE TITLE
Fix broken playlist images

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#491]
https://github.com/sudara/alonetone/pull/475 broke all the old/legacy playlist images on white theme.

https://github.com/sudara/alonetone/pull/475/files#r270474998 has more detail.

**Comment by sudara** [comment]
Solved with

```
Playlist.joins(:pic).where('pics.id between 0 and 69807').update(cover_quality: :ancient)
Playlist.joins(:pic).where('pics.id between 69806 and 72848').update(cover_quality: :legacy)
```

**Comment by innatewonderer** [comment]
You mean you created and properly reviewed/tested migration/one-shot file that got deployed and ran? :D

**Comment by sudara** [comment]
Yes! Exactly. Github has a new "Invisible PR" feature. 😈 Uhh, this was affecting production pretty badly, so I cheated and used the console.... Guilty as charged!
