### ISSUE TITLE
AbstractController::ActionNotFound in GET /admin/assets/111661/spam

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#521]
## Error in alonetone

**AbstractController::ActionNotFound** in **GET /admin/assets/111661/spam**
The action 'show' could not be found for Admin::AssetsController

[View on Bugsnag](https://app.bugsnag.com/alonetone/alonetone/errors/5c8c1ecc491d7d001a9043d1?event_id=5ca6634c0037e81e74dc0000&i=gh&m=ci)

## Stacktrace

    vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.0.beta3/lib/abstract_controller/base.rb:131 - process

[View full stacktrace](https://app.bugsnag.com/alonetone/alonetone/errors/5c8c1ecc491d7d001a9043d1?event_id=5ca6634c0037e81e74dc0000&i=gh&m=ci)

*Created by sudara via Bugsnag*

**Comment by sudara** [comment]
@innatewonderer Mind taking a look? Looks like we had a spike of these (maybe because i was being active in the admin area?) but the original error is from a while back.

**Comment by sudara** [comment]
An error linked to this issue has been reopened in Bugsnag
[**AbstractController::ActionNotFound** in **GET /admin/assets/26803/spam**](https://app.bugsnag.com/alonetone/alonetone/errors/5c8c1ecc491d7d001a9043d1?event_id=5cb2461e0037da5234be0000&i=gh&m=ra)

**Comment by innatewonderer** [comment]
closing.

**Comment by sudara** [comment]
An error linked to this issue has been reopened in Bugsnag
[**AbstractController::ActionNotFound** in **GET /admin/assets/73911/spam**](https://app.bugsnag.com/alonetone/alonetone/errors/5c8c1ecc491d7d001a9043d1?event_id=5cc26f500038d997e4fa0000&i=gh&m=ra)

**Comment by innatewonderer** [comment]
Found the reason. will push PR soon.

**Comment by sudara** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**AbstractController::ActionNotFound** in **GET /admin/assets/6412/spam**](https://app.bugsnag.com/alonetone/alonetone/errors/5c8c1ecc491d7d001a9043d1?event_id=5cd9cad20039ecb4bcee0000&i=gh&m=fx)

**Comment by sudara** [comment]
An error linked to this issue has been reopened in Bugsnag
[**AbstractController::ActionNotFound** in **GET /admin/assets/6334/spam**](https://app.bugsnag.com/alonetone/alonetone/errors/5c8c1ecc491d7d001a9043d1?event_id=5cd9cb13003a01476b200000&i=gh&m=ra)

**Comment by sudara** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**AbstractController::ActionNotFound** in **GET /admin/assets/6318/spam**](https://app.bugsnag.com/alonetone/alonetone/errors/5c8c1ecc491d7d001a9043d1?event_id=5cd9cb7d0039fb98ed260000&i=gh&m=fx)
