### ISSUE TITLE
On mass_edit, no feedback on save button is disconcerting.

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#531]
We want to use the exact same pattern (and UI) for saving on `mass_edit` that we do with comments.

This will probably mean creating a stimulus controller like `comment_controller.js.` We can coordinate with @ofsound on the PR to make sure styles are reusable.

**Comment by sudara** [comment]
We should discuss incorporating #533 into this...having a UI element display if the track came back as marked as spam. 

We could also discuss removing spam detection from tracks now that we are performing spam detection on users.... or somehow making that more sophisticated? It seems pretty annoying and unnecessary for an otherwise established user to suddenly get a track caught in the spam filter....

**Comment by sudara** [comment]
I guess we can "wait and see" how user spam detection goes. If that pretty much blocks spammy tracks from being uploaded, maybe we can eventually remove spam detection for tracks...

**Comment by ofsound** [comment]
Seems like single track upload is the same as mass edit as far as this goes? I've noticed when uploading a new track, entering a new description or title, then clicking save, you don't get a jump to a new flash message... or I guess I'd expect in that case to be re-directed back to the home or my user page?
