### ISSUE TITLE
Bulk Track Notification email should send on track creation, not on mass_edit

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#553]
Just got this in the mail today.

![alonetone  'montgomeru' uploaded new tracks! - sudara@modernthings net - Modern Things Mail 2019-04-27 18-54-36](https://user-images.githubusercontent.com/472/56852645-07a99380-691e-11e9-987f-a63772d46003.jpg)

Basically, it's an email notification that ben re-uploaded all his tracks, which he didn't do. What he did was visit mass_edit.

It looks like we are sending out the bulk notification on a GET visit to mass_edit, which is undesirable. We want to send the email out shortly after upload, but give enough time for people to fill out mass_edit...

Also, some of the wording here needs love — it shouldn't be "a track" —  it might be nice to say how many tracks were uploaded to visually distinguish it in the upload list. We should remove the single quotes around 'montgomeru' in the subject in both this email and the normal one too...

**Comment by sudara** [comment]
It fired right after the normal track notification email

<img width="923" alt="image" src="https://user-images.githubusercontent.com/472/56852707-ded5ce00-691e-11e9-8fea-c185cc786c3a.png">

**Comment by sudara** [comment]
It looks like a notification will go out on any "mass edit": https://github.com/sudara/alonetone/blob/master/app/controllers/assets_controller.rb#L132-L134

This means just by visiting mass_edit, email is being triggered.

We only want notifications to go out for newly uploaded tracks.

**Comment by innatewonderer** [comment]
We send everyone who is creating an asset that's not `@playlist` to `mass_edit`
https://github.com/sudara/alonetone/blob/master/app/controllers/assets_controller.rb#L164
Hence, the logic of the email
