### ISSUE TITLE
Changing image variant transformation options

### ISSUE THREAD

**Issue by Manfred** [sudara/alonetone#592]
## How things work

Images (and videos) can have variants in Active Storage. Variants are defined by their operations and Active Storage is set up to generate these just-in-time.

```ruby
resize_to_fit: [200, 200]
```

There are two ways to deal with variants and then I will explain how we currently do it in Alonetone.

For the upcoming examples, I'm going to assume there is a `variant` variable, which is assigned like this:

```ruby
variant = playlist.cover_image.variant(
  resize_to_fit: [200, 200]
)
```

### Representations controller

When you add `<%= image_tag(variant) %>` to your template you will create an `<img>` tag pointing to the representations controller. The Active Storage engine has a route like this:

```ruby
# variation_key contains the serialized and signed
# contents of the transformation options
/representations/:signed_blob_id/:variation_key/*filename
```

The controller ensures the variant on S3 and then redirects to a presigned S3 URL. Ensuring the variant has a number of steps:

* HEAD request to object
* If exists: do nothing
* If missing: call `processed` to generate and upload the variant

The controller also sets Etag, modified, etc headers to allow the browser to cache the image efficiently.

### Calling processed

Alternatively you can call processed from the template by using `<%= image_tag(variant.processed) %>`. This obviously makes rendering the template potentially very slow when variants have to be generated but has the upside that it can be cached pretty well (but not longer than the S3 URL expiration).

### What Alonetone currently does

When an image is uploaded Alonetone processes all variants:

```ruby
variants.each do |transformations|
  playlist.cover_image.variant(**transformations).processed
end
```

This means all variants should be on S3 and we can just generate a URL to S3 or CloudFront knowing that it should be able to serve the image.

## Changing variants

There is no Active Storage solution for changing these transformation options. Let's take the situation where we want to change the variation operations:

```ruby
# from
resize_to_fit: [200, 200]
# to
resize_to_fill: [200, 200], saver: { quality: 68, optimize_coding: true, strip: true }
```

What happens:

* It effectively orphans S3 objects fro previously generated variants
* Files for the new operations have to re-generated

To keep our previously generated variants from getting lot we would have to copy existing S3 objects to the new `key` and schedule deletion of the old variants. Immediate deletion would break the site until the new code is deployed.

### Hijack the representations controller solution

We can hijack the representations controller and implement a version that returns a CloudFront URLs. This allows us to remove `variants/*` from S3 and lazily generate the new variants we need. Downside is added latency when fetching images due to processign and redirect.

**cold**

* GET https://alonetone.com/representations/a3d7/45e7/original.jpg
* HEAD https://s3.amazonaws.com/alonetone/a3d7/45e7/original.jpg
* vipsthumbnail original.jpg
* PUT https://s3.amazonaws.com/alonetone/a3d7/45e7/original.jpg
* redirect_to https://cdn.alonetone.com/representations/a3d7/45e7/original.jpg

**hot**

* GET https://alonetone.com/representations/a3d7/45e7/original.jpg
* HEAD https://s3.amazonaws.com/alonetone/a3d7/45e7/original.jpg
* redirect_to https://cdn.alonetone.com/representations/a3d7/45e7/original.jpg

### Change CloudFront to use alonetone.com as origin

We can change CloudFront to use alontone.com and the representations controller route as origin. This allows us to remove `variants/*` from S3 and lazily generate the new variants we need. Improvement relative to previous solution is that it shifts responsibility of caching files to CloudFront and removes latency entirely when cache is hot.

/representations/:signed_blob_id/:variation_key/*filename

**cold**

* GET https://cdn.alonetone.com/representations/a3d7/45e7/original.jpg
* GET https://alonetone.com/representations/a3d7/45e7/original.jpg
* HEAD https://s3.amazonaws.com/alonetone/a3d7/45e7/original.jpg
* vipsthumbnail original.jpg
* PUT https://s3.amazonaws.com/alonetone/a3d7/45e7/original.jpg
* self.response_body = open('original.jpg')

**warm**

* GET https://cdn.alonetone.com/representations/a3d7/45e7/original.jpg
* GET https://alonetone.com/representations/a3d7/45e7/original.jpg
* HEAD https://s3.amazonaws.com/alonetone/a3d7/45e7/original.jpg
* self.response_body = open('original.jpg')

**hot**

* GET https://cdn.alonetone.com/representations/a3d7/45e7/original.jpg

### Keep the current approach and implement variation migration

When storing the generated variant a key is generated based on these options.

```ruby
# When unwrapping the call stack the code looks like this:
variation_key = Digest::SHA256.hexdigest(
  ActiveStorage.verifier.generate(
    transformations,
    purpose: :variation
  )
)
"variants/#{blob.key}/#{variation_key}"
```

So we can easily write a migration where we copy all S3 objects to their new location:

```ruby
ImageVariantMigration.create(
  from: { resize_to_fit: [200, 200] },
  to: { resize_to_fill: [200, 200], saver: { quality: 68, optimize_coding: true, strip: true } }
)
```

When we persist this information we can delete the old objects once the code has been deployed.

1. First run: copy or generate all new variants
2. Take down Alonetone
3. Second run: copy or generate all new variants for recently uploaded files
4. Deploy new version of Alonetone
5. Delete objects for old variants

Result is that we are always warm.

**warm**

* GET https://cdn.alonetone.com/representations/a3d7/45e7/original.jpg
* GET https://s3.amazonaws.com/alonetone/a3d7/45e7/original.jpg

**hot**

* GET https://cdn.alonetone.com/representations/a3d7/45e7/original.jpg

**Comment by Manfred** [comment]
### Bonus option

Finally as a bonus alternative we can move variant generation out of Active Storage and to [NGINX + ngx_http_image_filter_module](http://nginx.org/en/docs/http/ngx_http_image_filter_module.html).

```
location /scaled/ {
  proxy_pass http://127.0.0.1:10101;
  proxy_cache nginx_cache;
  proxy_cache_key "$proxy_host$uri";
  proxy_cache_valid 7d;
  expires 7d;
}

# Proxy to resize image data
server {
  listen 10101;
  server_name image.alonetone.com;
  location ~ ^/scaled/([0-9]+)x([0-9]+)/(.+) {
      error_page 415 =404 /public/images/blank.jpg;
      image_filter_buffer 128M;
      image_filter_jpeg_quality 68;
      image_filter_interlace off;
      image_filter resize $1 $2;
      rewrite ^ $request_uri;
      rewrite ^/scaled/([0-9]+)x([0-9]+)/(.*) $3 break;
      return 400;
      proxy_pass http://127.0.0.1:10102/$uri;
      proxy_cache_valid 200 7d;
      expires 7d;
  }
}

# Proxy to fetch data from AWS S3
server {
    listen 10102;
    resolver 1.1.1.1;
    resolver_timeout 60s;
    set $backend alonetone-production.s3.eu-central-1.amazonaws.com;
    proxy_buffering on;
    proxy_http_version 1.1;
    proxy_pass_request_body off;
    proxy_pass_request_headers off;
    proxy_hide_header "x-amz-id-2";
    proxy_hide_header "x-amz-request-id";
    proxy_hide_header "x-amz-storage-class";
    proxy_hide_header "Set-Cookie";
    proxy_ignore_headers Set-Cookie Cache-Control;

    proxy_connect_timeout   60;
    proxy_send_timeout      60;
    proxy_read_timeout      60;

    location ~ ^/(.+) {
        rewrite ^ $request_uri;
        rewrite ^/(.*) $1 break;
        return 400;
  
        proxy_pass https://$backend/$uri;
        error_page 415 =404 /public/images/blank.jpg;
        proxy_cache nginx_cache;
        proxy_cache_key "temp_$proxy_host$uri";
        proxy_cache_lock on;
        proxy_cache_valid 200 7d;
        expires 7d;
    }
}
```

Which totally side-steps the variants code in Active Storage and just generates URLs to the image. You could put CloudFront in front of this as well as a CDN.

**Comment by sudara** [comment]
Thanks for this write up! 

It's unfortunate that the rails default is to download, process, upload a file *inside* the request cycle. Not only is that a poor user experience, but it also clogs rails processes/threads. Perhaps the expectation is that the user uploading experiences the thumbnail delays themselves, so it's "understandable" from a usability perspective. Also, I guess generating 6+ variants in the request cycle on upload (like we are doing now) isn't a silver bullet, though there is (more) user expectation that "I'm uploading, this takes time."

I'll give this a bit more thought and reading. My knee jerk for what we should do is:

1) Figure out what variants we need "for reals" (get rid of 25x25, add 200x200).

2) Remove variants/* on s3

3) Re-run the migrate script.

4) Hope we never have to change the variant settings en-masse, only add/remove em.

5) Hope we don't grow too large.

---

But I will think through the caching issues. I'd like to invest a bit of thinking in future-proofing. So I'm thinking about questions like:

1) When we have 500k covers and avatars, it's going to be unfriendly to download them all to generate variants. So, some "lazy" generation is going to make sense otherwise we are in Backfill City™ 🌇 

2) If we go the route of cloudfront caching from the app and ever have to flush cache, it's going to make browsing fairly miserable and clunky. 

3) Why doesn't the representation controller implementation support cloudfront natively. That's sort of red flaggy to me but looks like it's easy to work around https://github.com/gitcoinco/code_fund_ads/pull/115/files

**Comment by Manfred** [comment]
> It's unfortunate that the rails default is to download, process, upload a file inside the request cycle.

Active Storage was built to be a simple drop-in solution for file uploads for most people. I'm guessing their reasoning is that large websites with lots of traffic will have to implement their own specific solution anyway.

They probably wanted to avoid any kind of background processing because it would require shared filesystems between web and background servers.

I'm guessing the design decision was that networks and servers are fast enough to deal with synchronous processing when you have a site that takes less than 1rpm traffic.

Also; nobody generates 6 variants, you really shouldn't need more than 2 every IMO.

> If we go the route of cloudfront caching from the app and ever have to flush cache, it's going to make browsing fairly miserable and clunky.

Yeah, maybe for the first 5 minutes or so, I don't think there are that many images on Alonetone that are seen frequently.

> Why doesn't the representation controller implementation support cloudfront natively.

CDNs work best for sites that take repeated traffic to the same assets. I'm willing to bet that most sites using Rails are internal or authenticated sites and only a handful of users look at the same images. Using an edge network solution is going to have very little impact on the speed of those sites. Also; I think people will eventually merge some sort of CDN support into Active Storage.

**Comment by sudara** [comment]
How I'm seeing things right now:

## Variants created on upload, stored on s3, served by Cloudfront
❤️ Consistently fast, single GET request to cloudfront per image
❤️ Doesn't pollute the alonetone rails server with image requests
❤️ CPU from Variant creation depends on write behavior, not read behavior 
👎 New Variant sizes are hard to make. D/L all originals and iterate through them. Backfill City™ 🌇 
❓ Potential tipping point where backfilling becomes cost prohibitive? Unlikely to hit anytime soon, we are at 20k pictures, 5gb originals. 

## Variants lazily created, served by Cloudfront with TTL of 1 year
❤️ When cache is warm, Consistently fast, single GET request to cloudfront per image
❤️ Ability to modify variants easily without need for migrations or redownloading originals
👎 Degrades UX when cache is cold, adds a minimum of ~500ms latency.
👎 Every image request is now a request to rails/puma, goes against Performance 101 best practices, images not served when rails app down.
❓ An increase in traffic potentially results in an increase of rails requests / vips CPU. I was thinking googlebots etc might keep cloudfront cache warm for the long tail, but actually it'll likely only do that for 1 or 2 edge locations.

**Comment by Manfred** [comment]
I don't think it's very hard to do a quick and dirty implementation of the second way on my development setup if you want to know how slow it actually gets.

**Comment by sudara** [comment]
I'm fairly reluctant to send all image requests through Rails. I'm wondering if there's a hybrid solution where we can serve Cloudfront URLs, it checks s3, if variant isn't present, it's built.

**Comment by sudara** [comment]
Looks like the migration was ~50 bucks even for our small amount of data, mainly for GetObject.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/472/57786944-be867b80-7734-11e9-8f6d-0360c54f39bd.png">

**Comment by sudara** [comment]
🌞
