### ISSUE TITLE
Clicking headway gray circle in the header on mobile, requires a scroll to show the overlay

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#598]

**Comment by sudara** [comment]
@ofsound Is this fixed? Not seeing it here on the iphone...

**Comment by ofsound** [comment]
Looks like it's just an issue when the vertical height of headway is more than the screen height. I don't encounter it on split iPad views, only on my small 320px iPhone.

**Comment by sudara** [comment]
I can reproduce this holding my phone horizontally. Potentially a headway bug?

**Comment by sudara** [comment]
No longer relevant since we killed headway on mobile for now.
