### ISSUE TITLE
Admin css tweaks

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#619]
1. Search box might be nice to float right( in horizontal line with pagination). Or otherwise style as you like!

2. I'd like to show the "deleted at" date but have it be a different color.
<img width="410" alt="image" src="https://user-images.githubusercontent.com/472/59644835-ff781280-916e-11e9-8c9c-fc99d034221a.png">

3. Would be sweet if hovers went full width of nav.
<img width="242" alt="image" src="https://user-images.githubusercontent.com/472/59644898-54b42400-916f-11e9-8683-fbc7d5cbf056.png">

4. I'd like to add counts to the navigation like "Only Spam (34)", would be cool to get a placeholder there.

**Comment by ofsound** [comment]
@sudara 

Check out my branch https://github.com/sudara/alonetone/tree/bjm_admin_css_tweaks

This should address these 4 things, but didn't want to officially do a draft Pull Request, as maybe there are some other things that could be included.

The (9999) user counts are all just total users now.

Opening to /admin is suspiciously empty, maybe if nothing is going to go there, we should just open to admin/users?
