### ISSUE TITLE
Bugsnag: features#show

### ISSUE THREAD

**Issue by innatewonderer** [sudara/alonetone#649]
Issue from [bugsnag](https://app.bugsnag.com/alonetone/alonetone/errors/5bd3eb9be24a4f0018388e94?filters[app.type][0][value]=rails&filters[app.type][0][type]=eq)
```
undefined method `featured_user' for nil:NilClass
```
This URL should not be hit. There are no direct link to it, and all errors I checked on Bugsnag appears to be done by bots.
Suggesting fixes:
1. delete/hide route
2. handle if no feature found

**Comment by sudara** [comment]
No longer an issue.
