### ISSUE TITLE
Assets soft deleted from a user's soft delete are not handling all dependencies (track, comment(?), etc)

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#653]
In the case of this bugsnag, the `asset` is present, but deleted (probably because its parent user was deleted) — so in the context of a playlist, the `track.asset.id` is `nil`.

```
irb(main):011:0> playlist.tracks.collect {|t| Asset.with_deleted.find(t.asset_id) }.count
=> 69
irb(main):012:0> playlist.tracks.collect {|t| Asset.find(t.asset_id) }.count
Traceback (most recent call last):
        3: from (irb):12
        2: from (irb):12:in `collect'
        1: from (irb):12:in `block in irb_binding'
ActiveRecord::RecordNotFound (Couldn't find Asset with 'id'=34775 [WHERE `assets`.`deleted_at` IS NULL])
irb(main):014:0> Asset.with_deleted.find(34775)
=> #<Asset id: 34775, mp3_content_type: "audio/mpeg", mp3_file_name: "stronger_together.mp3", mp3_file_size: 8845695, created_at: "2011-03-12 22:11:27", title: "Stronger Together", thumbnails_count: 0, user_id: 4354, length: 221, album: nil, permalink: "stronger-together", samplerate: 48000, bitrate: 320, genre: nil, artist: "Dave McCormick", listens_count: 198, description: "", credits: nil, youtube_embed: "", hotness: 0.00212567, favorites_count: 2, lyrics: nil, description_html: nil, listens_per_week: 0.0, comments_count: 4, updated_at: "2019-03-03 01:33:26", private: false, id3_track_num: 1, is_spam: false, deleted_at: "2019-04-04 08:08:30", user_agent: nil>
```

## Error in alonetone

**ActionView::Template::Error** in **playlists#show**
undefined method `id' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/alonetone/alonetone/errors/5d11938673d2380018dee246?event_id=5d4fa727004ccce11ae50000&i=gh&m=ci)

## Stacktrace

    app/views/playlists/_playlist_white.html.erb:14 - block in _app_views_playlists__playlist_white_html_erb__321828785332572429_69857178009000
    app/views/playlists/_playlist_white.html.erb:13 - _app_views_playlists__playlist_white_html_erb__321828785332572429_69857178009000
    app/views/playlists/show_white.html.erb:8 - _app_views_playlists_show_white_html_erb__2439390540724164419_69857177562100
    app/controllers/playlists_controller.rb:48 - block (2 levels) in show
    app/controllers/playlists_controller.rb:41 - show

[View full stacktrace](https://app.bugsnag.com/alonetone/alonetone/errors/5d11938673d2380018dee246?event_id=5d4fa727004ccce11ae50000&i=gh&m=ci)

*Created by sudara via Bugsnag*

**Comment by innatewonderer** [comment]
It should have deleted `tracks` if a user is deleted :/  That's what I don't understand.
I'll dig into it.

**Comment by sudara** [comment]
I think we are only deleting the tracks that users create. Not the ones that other users make with their assets. Likely this was a problem manifesting in some other way before soft deletion, is my guess!

**Comment by innatewonderer** [comment]
`Track.with_deleted.joins(:asset).where(assets: { user_id: id }).update_all(deleted_at: nil)` from [here](https://github.com/sudara/alonetone/blob/master/app/models/user.rb#L305)

You are correct.
I'll fix it with the use of command pattern :)

**Comment by sudara** [comment]
The work on #671 makes this look like a one off data issue. I manually removed the offending track/asset and have marked the bugsnag as resolved. If it pops up again we can handle it.

**Comment by sudara** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionView::Template::Error** in **playlists#show**](https://app.bugsnag.com/alonetone/alonetone/errors/5d11938673d2380018dee246?event_id=5d5d7027004d8540aba20000&i=gh&m=ra)

**Comment by innatewonderer** [comment]
So the bot is still trying to hit that URL:
https://alonetone.com/02bfree/playlists/relax-your-mind/the-broken-rain
If the tracks were deleted...  how does it... ???

**Comment by sudara** [comment]
```ruby
irb(main):080:0> no_asset = []
=> []
irb(main):081:0> Track.in_batches.each_record do |track|
irb(main):082:1* no_asset << track.id unless track.asset.present?
irb(main):083:1> end
=> nil
irb(main):084:0> no_asset
=> [58208, 75233, 81044, 83471]
irb(main):072:0> tracks.collect {|t| Track.find(t).playlist.title }
=> ["crackitopen's Favorite tracks on alonetone", "Relax Your Mind", "Relax Your Mind", "Relax Your Mind"]
```

These 4 tracks were attached to assets that were soft deleted from a user that was hard deleted.

They have been manually removed on production.
