### ISSUE TITLE
Admin comment moderation on the home page has shown some inconsistency in which comments can be deleted/marked

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#658]

**Comment by ofsound** [comment]
![Screenshot 2019-08-13 13 37 58](https://user-images.githubusercontent.com/407724/62971730-c0151d80-bdcf-11e9-8209-2f09fa637891.png)

**Comment by sudara** [comment]
This is the result of using collection caching in latest_white.html.erb — options are to 

1. Stop using collection caching and manually call `cache` inside `shared/comment` with `authorized_for_comment?` as a part of the cache key

2. always render the moderator links set to `display:none` and toggle them visible with js when user is a mod (this actually might not be an option, as we have no way of knowing if current_user is the creator of the comment)

**Comment by sudara** [comment]
For 2:

* [ ] Always include `delete` / `spam` links in Rails comment html
* [ ] Adding stimulus controller to the comment (would have to deal with the fact that we already name one of the controllers comment_controller) 
* [ ] Adding a data attribute to comment with the user_id of the owner
* [ ] Check out `_javascript_payload.html.erb` and make sure we are passing in the current user id
* [ ] On initialize of the controller, we check to see if use is owner, if so, unhide the `delete` button. 
* [ ] Check to see if user is mod, if so unhide the `spam` button
* [ ] Add Feature/percy tests for each (or manipulate existing tests to add regression coverage).
