### ISSUE TITLE
Soft Delete Tracks marked as spam

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#672]
Followup to #636.

Assets marked as spam currently do *not* show in the UI because we manually pepper in the the scope `not_spam` everywhere.

We want to keep that UI behavior but move to the more formal mechanism to remove tracks from the UI (soft deletion) — This is in line with how user spam+soft deletion works.

* [x] Everywhere an asset is marked as spam, we need to soft delete
* [x] Remove `not_spam` scope
* [x] Make sure admin UI is sane with buttons — should be similar to users UI in terms of what buttons show

**Comment by innatewonderer** [comment]
[ ] include one-shot (migration) to soft_delete all spam assets (otherwise they will all show up on Latest.

**Comment by innatewonderer** [comment]
<img width="767" alt="Soft_Delete_Tracks_marked_as_spam_·_Issue__672_·_sudara_alonetone" src="https://user-images.githubusercontent.com/2320322/63198370-80a53600-c048-11e9-81b4-5ad0e1515af9.png">

**Comment by sudara** [comment]
Fixed by #673
