### ISSUE TITLE
Fastly setup

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#676]
Fastly has enabled IO, so we can proceed with setting up image resizing. The requirements before IO was enabled included all `hosts` having a `shield` specified, ideally as close (in network terms) to the host as possible.

I'd like to have 1 domain, `fastly.alonetone.com` serve the following, in order of priority:

* Profile images from s3 `host`, thumbnailed on the fly
* css/js from alonetone.com
* Fonts from s3 (this will require CORS support / ensuring the referrer is alonetone.com, we don't want to serve our fonts to any website)
* app images from alonetone.com

Points of interest and open issues:

1. I currently have 2 `hosts` (s3/alonetone) setup in fastly under 1 `service` to work towards this goal of having as much static content as possible serve from 1 domain / 1 dns lookup. If there are good reasons to add another `service`/`domain` we can do that as well.

2. Our account includes a "shared TLS wildcard certificate" — do we need this? 

3. "Full Site Delivery" implies we should put fastly as a varnish cache in front of all of alonetone — I'm assuming we don't get much value from this, but it's a point of discussion. 

4. We created a ton of "variants" and uploaded to s3 — can we remove them? (they clutter the root of the bucket, obscuring the folders)

5. How will variants work locally? I'm assuming I'll lose the ability to use production images locally.

/cc @Manfred

**Comment by Manfred** [comment]
> Is there are good reasons to add another service/domain we can do that as well.

Not really, I think you can configure Varnish to match on paths right?

**Comment by sudara** [comment]
https://docs.fastly.com/legal/tls-service-options#shared-tls-wildcard-certificate-service

From what I can tell, this would let us use a cert to serve off of unlimited alonetone.com subdomains.

However, looks like the account is not yet enabled to setup domains properly https://manage.fastly.com/account/tls/domains

**Comment by sudara** [comment]
@manfred Image Optimizer seem happy & ready for app dev. Fastly is connecting to the public bucket over port 80 via the `stash.alonetone.com` and is keying off `^/pics` as the regex.

Tangent: I sort of regret setting `content-disposition: attachment;` as the default for s3, it's been pretty annoying to work with.

```➜  ~ curl -I https://fastly.alonetone.com/pics/84545/A211703D-531D-49A4-AD6A-BDCDCF7446B0_greenfield.jpeg\?width\=400
HTTP/2 200 
content-disposition: attachment;
content-type: image/jpeg
etag: "x+1lkO8D0caWVLO/UsTFMlU9eP8wuf4VqYntMNd23II"
expires: Mon, 08 Aug 2022 21:55:07 GMT
fastly-io-info: ifsz=192504 idim=1500x1500 ifmt=jpeg ofsz=35765 odim=400x400 ofmt=jpeg
fastly-stats: io=1
server: AmazonS3
x-amz-id-2: ckac38gVmp9qkdmpLganneZRPDCiB//aGa0G/YTWPeCYz9POgRBTaUAxE23A94aiBSTLlKW5PSI=
x-amz-request-id: 47F1CCC210CA6A1F
x-amz-version-id: wFW6SswhurIEaFtj0tLqZmL0_0ghxf86
via: 1.1 varnish
accept-ranges: bytes
date: Fri, 23 Aug 2019 14:13:35 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-dca17757-DCA, cache-hhn4050-HHN
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1566569616.798133,VS0,VE143
content-length: 35765

➜  ~ curl -I https://fastly.alonetone.com/pics/84545/A211703D-531D-49A4-AD6A-BDCDCF7446B0_greenfield.jpeg\?width\=400
HTTP/2 200 
content-disposition: attachment;
content-type: image/jpeg
etag: "x+1lkO8D0caWVLO/UsTFMlU9eP8wuf4VqYntMNd23II"
expires: Mon, 08 Aug 2022 21:55:07 GMT
fastly-io-info: ifsz=192504 idim=1500x1500 ifmt=jpeg ofsz=35765 odim=400x400 ofmt=jpeg
fastly-stats: io=1
server: AmazonS3
x-amz-id-2: ckac38gVmp9qkdmpLganneZRPDCiB//aGa0G/YTWPeCYz9POgRBTaUAxE23A94aiBSTLlKW5PSI=
x-amz-request-id: 47F1CCC210CA6A1F
x-amz-version-id: wFW6SswhurIEaFtj0tLqZmL0_0ghxf86
via: 1.1 varnish
accept-ranges: bytes
date: Fri, 23 Aug 2019 14:13:38 GMT
via: 1.1 varnish
age: 3
x-served-by: cache-dca17757-DCA, cache-hhn4071-HHN
x-cache: MISS, HIT
x-cache-hits: 0, 1
x-timer: S1566569619.766945,VS0,VE40
content-length: 35765
```

**Comment by sudara** [comment]
CSS/JS and app images can now be served from fastly.

```
➜  alonetone git:(master) curl -svo /dev/null https://fastly.alonetone.com/assets/white_theme-5119198ac9b1a22f55bbbc08bc3834fefcec4d3999476032862ad0ade9b5f68a.css
*   Trying 151.101.114.217...
* TCP_NODELAY set
* Connected to fastly.alonetone.com (151.101.114.217) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [234 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3888 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Fastly, Inc.; CN=h3.shared.global.fastly.net
*  start date: Aug 25 07:44:21 2019 GMT
*  expire date: Jun 18 19:18:04 2020 GMT
*  subjectAltName: host "fastly.alonetone.com" matched cert's "*.alonetone.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign CloudSSL CA - SHA256 - G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8919002800)
> GET /assets/white_theme-5119198ac9b1a22f55bbbc08bc3834fefcec4d3999476032862ad0ade9b5f68a.css HTTP/2
> Host: fastly.alonetone.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< server: nginx/1.15.8
< content-type: text/css
< last-modified: Wed, 21 Aug 2019 12:37:20 GMT
< etag: "5d5d3b00-1caec"
< strict-transport-security: max-age=63072000; includeSubdomains; preload
< x-frame-options: DENY
< x-content-type-options: nosniff
< via: 1.1 varnish
< accept-ranges: bytes
< date: Mon, 26 Aug 2019 15:05:40 GMT
< via: 1.1 varnish
< age: 6
< x-served-by: cache-ewr18137-EWR, cache-hhn4039-HHN
< x-cache: MISS, HIT
< x-cache-hits: 0, 1
< x-timer: S1566831941.743616,VS0,VE7
< vary: Accept-Encoding
< content-disposition: inline
< content-length: 117484
< 
{ [2434 bytes data]
* Connection #0 to host fastly.alonetone.com left intact
* Closing connection 0
```

**Comment by sudara** [comment]
css/js Before fastly:
<img width="798" alt=" 2019-08-26 17-24-23" src="https://user-images.githubusercontent.com/472/63702028-72b09b80-c826-11e9-8efa-7a97e208fff2.png">

css/js After fastly:
![ 2019-08-26 17-21-21](https://user-images.githubusercontent.com/472/63701836-0a61ba00-c826-11e9-8b96-5552f901ae37.png)

**Comment by Manfred** [comment]
@sudara do you have an example of a URL that went through the Image Optimizer properly? I have the feeling that it's not working properly because I'm getting S3 responses without resizing.

Also; I still see certificate issues with this URL for example:

`https://stash.alonetone.com/pics/81477/IMG_4317_greenfield.JPG?quality=68&width=20`

**Comment by Manfred** [comment]
<img width="448" alt="Screenshot 2019-09-17 at 15 57 59" src="https://user-images.githubusercontent.com/1195/65048240-14c62e00-d964-11e9-8771-2c3c797430f3.png">

I'm pretty sure this causes a request for something on S3 that ends with `jpeg` to actually end up on Linode. So I think the second `if` should be replaced with an `else if`.

**Comment by sudara** [comment]
These conditions are executed in order of priority, similar to nginx (vs. using if/else logic). So, the first condition will match anything starting with `/pics` and execute the logic there.

This can be found in the UI here:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/472/65049165-9c606c80-d965-11e9-9dcc-cde63fbd421b.png">

**Comment by sudara** [comment]
> Also; I still see certificate issues with this URL for example:
> https://stash.alonetone.com/pics/81477/IMG_4317_greenfield.JPG?quality=68&width=20

The s3 bucket doesn't support https, we do that via cdn.alonetone.com which is cloudfront.

**Comment by Manfred** [comment]
Alright, everything seems to work. I think we can close this issue.
