### ISSUE TITLE
Playlist View Single Player Seekbar is less consistent in Chrome than in FF or Safari

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#719]
https://alonetone.com/coelocanth/playlists/as-if-a-dream/peach-and-aberge

In Chrome, If I start this track and then seek forward it doesn't work, but also doesn't send an error.

Also problems with seeking from a paused state.

Doesn't seem to happen on the same page in FF or Safari.

AND doesn't seem to happen on the Single Track page.

( macOS )

**Comment by sudara** [comment]
I can't reproduce — although seeking very quickly does briefly change the time to NaN sometimes.
