### ISSUE TITLE
In playlist player auto play, big play animation can land in confused state

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#729]
Perhaps fixable with #666 

<img width="398" alt="Screenshot 2019-09-07 11 15 42" src="https://user-images.githubusercontent.com/407724/64478140-1bcd8f00-d161-11e9-8b7f-27dba7ff70d9.png">

**Comment by sudara** [comment]
Oooh, thanks for catching. We can use https://alonetone.com/sudara/playlists/continue to help reproduce / troubleshoot this.

**Comment by sudara** [comment]
This looks to be an SVG visibility thing that I can't quickly figure out how to reproduce. 

@ofsound any interest in tracking it down and shipping a part of #730?

**Comment by sudara** [comment]
Actually, this is closed already in #730. The issue was that we needed to call `showLoading()` before `showPause()` -- the svg was unhappy transitioning directly to a pause state without having gone through the loading one.

**Comment by sudara** [comment]
Although..... we might want to actually have a way for the svg to transition immediately — right now if you press play on a track in a playlist, navigate to another track and back, the animation always shows up. Not a huge deal, but...
