### ISSUE TITLE
Forgot your login?

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#74]
ARG.

**Comment by sudara** [comment]
This is the #1 support request on the site right now, would love to make it high priority.

I'm not 100% what the right solution is, but I keep getting emails like:

![2015-02-01 alex moody - sudara mark williams](https://cloud.githubusercontent.com/assets/472/5990278/b864a504-a9a9-11e4-8d35-97f5f268b0b4.jpg)

**Comment by sudara** [comment]
Wondering if it may be email deliverability issue. I thought it was UI/browser issue like the request wasn't being submitted right.

But people complain about not getting the mail. This last request, I triggered it and the guy still didn't get it. On a hotmail account.

**Comment by wioux** [comment]
Closing this. Let's see whether it's still an issue with the new delivery method.
