### ISSUE TITLE
Local asset spec failures

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#755]
Seeing these fail on my machine but not on CI:

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/472/64966879-e54ded80-d89f-11e9-873a-feb38b766eb4.png">

I thought maybe this is related to #732 and the fact that I removed collation from database.yml (default on mysql 8 is not to specify collation) — but perhaps unrelated.

**Comment by Manfred** [comment]
@sudara Can you run one of these specs in isolation and check test.log for errors?

**Comment by sudara** [comment]
Not seeing any errors in test.log.

**Comment by Manfred** [comment]
@sudara Do you still see these problems after yesterday's merge?

**Comment by sudara** [comment]
Yes, I’m still seeing these intermittently....

**Comment by sudara** [comment]
Haven't seen these for a while...
