### ISSUE TITLE
Blank Slate Illustrations

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#767]
Context in #606. These "blank slate" illustrations are paired with text and are meant to guide users during their first experiences making things on the site.

## Welcome to alonetone

Context: Give people an idea of what the place is.

Character: We talked about this being the "uke-head" on a desert island!

Text: Alonetone is your musical oasis away from serious release dates, social media strategies and sketchy startups. Breathe a sigh of relief of relief and upload what you are working on. 

Display dimensions: 250x250ish illustration within a 880x240px container (deliverable dimensions are 2x display width and height)

Samo and I have to work on layout again, but we are probably working with space like this:

## "What's a playlist?" on create playlist page

Could optionally include "What's a playlist?" as illustrated words here. 

Context: Different sites work differently with albums and collections and playlists — this is to guide users and let them know what's possible as well as what exactly that ambiguous term means. 

Character: Manfred explaining the tech details.

Text: On alonetone, a "playlist" is just what we call a group of tracks. This is the best way to collect demos you are working on, publish an album, or even to create a mix from various alonetone artists.

Display dimensions: 250x250ish illustration within a 880x240px container (deliverable dimensions are 2x display width and height)

## Go ahead and upload your first track

We could optionally include "Upload your first track!" as illustrated words here. 

Context: After activating an account, user is redirected to upload a track. It's somewhat daunting (also not yet designed, so it's crufty).

Text: Upload your first mp3. It can be something in progress, a demo, or a zip file full of mp3s of your latest album. It will be public right away, you can always adjust the title and description before sharing it.

Character: Ben, chill and encouraging. "Whatever you like!"

## Add a bio

Context: Prompt users to enter some info about themselves.

Character: Samo

Text: "Pfft, you haven't updated your profile yet?" or something sassy.

Display dimensions: I can check with samo, but we could potentially use all this whitespace to the right of the user's profile picture (400x400px-ish)... OR we can use the full space there if they didn't upload their pic. On mobile we are constrained to a square-like space, so it might be best to aim for the former.

## Empty Home

Context: A user's homepage is almost completely empty

Character: Jenya

Text: "Welcome to the farm — er, I mean your profile. Your playlists and tracks and activity will show up here once you start doing stuff!"

<img width="1471" alt="test1234's Music | alonetone 2019-10-03 20-16-40" src="https://user-images.githubusercontent.com/472/66152889-ba42f800-e61a-11e9-9e6b-5cd6d87c048c.png">

## About Alonetone

Context: Someone clicked "about" and wants to know what the deal is

Text: "alonetone is a place for small label, DIY, bedroom and other musicians and bands to upload and share their mp3s for free. We've been around since 2008."

**Comment by PhaseSevenComics** [comment]
_Me_ personally narrate the site?! How about a little cartoon _Sudara_ narrating the site??? 😉 Seriously though, I'll think about the fictional character idea some more....

Sounds like the "What's a Playlist?" illo is straightforward enough to be our test. Let me get some sketches cooked up this weekend and then folks can weigh in with what they think is working.

**Comment by sudara** [comment]
@PhaseSevenComics I added a couple more blank slates in the description here as well as gave temporary assignment / text to the blurbs.

I'm not 100% sure what we should do about text. I don't think it makes sense to do lettering. I think it should be clear by having text paired with the illustration that it's the characters speaking?...

**Comment by sudara** [comment]
I'm still on the hunt for a location for alec and sudara....

**Comment by PhaseSevenComics** [comment]
I agree that text should not be IN the image - that runs into accessibility problems (having to add the entire dialogue into the "alt" tag for vision-impaired users). I think if the character has an open mouth and is kind of gesturing in the right way, it'll be clear they are speaking. Adding quote marks to the text also goes a long way to anchoring it to the illustration. "See that button down there? Give it a click! That'll take you to bla bla bla"

Would it make sense to have a "team" page (in the "about" section?) where each member could have a little illo and info?

**Comment by sudara** [comment]
> I think if the character has an open mouth and is kind of gesturing in the right way, it'll be clear they are speaking. 

Thanks for that. Let's go this route!

> Would it make sense to have a "team" page (in the "about" section?)

Yes! I've been thinking about this. Might do first names and country. I figured if we did 2 versions of the contributors, one "speaking" and one "chilling" then we'll be set!

**Comment by sudara** [comment]
> Adding quote marks to the text also goes a long way to anchoring it to the illustration. 

Oooooh, good call. Thanks!

**Comment by sudara** [comment]
Regarding sizes — I think we should aim for 350px by 350px display (600x600 actual) with the understanding they might be displayed a bit smaller (250px x 250px) on mobile.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/472/66505830-662d8d00-eacc-11e9-9fe8-b06580806569.png">

**Comment by sudara** [comment]
@PhaseSevenComics We should be ready to roll on these! I've run into a couple more spots we can use a sudara / alec, I'll add them up top.

**Comment by PhaseSevenComics** [comment]
Perfect, thanks! I'll dig in and hopefully have a batch of stuff to you by the end of this weekend!
