### ISSUE TITLE
Admin users search should search "display_name" too

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#783]
https://alonetone.com/admin/users?filter_by=davidsen

should result in 
https://alonetone.com/kenneth
https://alonetone.com/ken

**Comment by fadib** [comment]
Hi @sudara, can I contribute to this issue? How can I signup to alonetone?

**Comment by sudara** [comment]
Hey fadib!

For sure on both accounts. We recently closed signups while we get our house in order with regards to spam. That's also been a motivation for building out the admin area.

I'm working on a contributing guide, but this particular issue would be a great way to dig in.

I'll send you an invite link.

**Comment by sudara** [comment]
@fadib Tried to invite you, but looks like your github email listed on your profile doesn't exist. You can email support@alonetone.com and I'll get you setup.

**Comment by fadib** [comment]
@sudara Sent you an email. Thanks!
