### ISSUE TITLE
Smaller "flavor" Illustrations

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#784]
I wanted to start a list of a few places where we could use some @PhaseSevenComics flavor in smaller touches, in part to answer type/style questions brought up here: https://github.com/sudara/alonetone/issues/606#issuecomment-533965293

https://alonetone.com/about is a good place to start. That will turn into a FAQ with a few more questions. I can imagine weaving a few illustrations throughout the text, a few themes being:

* WE ARE NOT A STARTUP! 
* THIS IS FOR ARTISTS-ONLY (no podcasts or labels)
* YES, IT'S FREE
* YES, IT'S OPEN SOURCE
* NO, U CANT SELL YOUR MUSIC

There's also an about/history page with some similar themes such as:

* ALONETONE IS SOCIAL
* WE'VE BEEN HERE FOR 10 YEARS (AND HOPE TO BE HERE DECADES MORE)
* BEDROOM MUSICIANS
* RELEASES vs. DEMOS

Additionally there are some "moments" around the UI that might benefit from little touches, such as when a user goes to delete their account, samo and I keep talking about there being a "shocked" face there, to help drive home it's a big deal.

<img width="1000" alt="alonetone white theme – Figma 2019-09-24 16-49-46" src="https://user-images.githubusercontent.com/472/65523088-08098300-deec-11e9-84c5-ed17770493f6.png">

The forums are incredibly dry and could use some pick me up, perhaps a small illustration per category (just need to make sure we have 

<img width="789" alt="image" src="https://user-images.githubusercontent.com/472/65523238-44d57a00-deec-11e9-900b-aac140f2568c.png">

**Comment by PhaseSevenComics** [comment]
I'm excited to jump in on all of these once we nail down the approach for the illustrations. Once that's locked in I can whip up a few ideas for each of these to make sure the illustrations are as clear and "witty/funny" as possible.

**Comment by sudara** [comment]
We mocked out how the forum could look. Seems like 96x96 is the display size there. 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/472/66717594-0c360b80-eddb-11e9-803d-d2da48a90bde.png">

<img width="822" alt="image" src="https://user-images.githubusercontent.com/472/66717609-25d75300-eddb-11e9-9dae-c457064cfc69.png">

**Comment by sudara** [comment]
Mocked up how things would look on new (not yet implemented) about pages and it seems like we could either do rectangular or square illustrations.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/472/66719871-a3a85800-edf5-11e9-800e-ae5898d5ff7e.png">

Adding a bit of color works on white, but is harder on dark backgrounds. White on black (inverted) looks absolutely great, so maybe we don't need color here. Or if so, we'd need to do it case by case...

<img width="582" alt="image" src="https://user-images.githubusercontent.com/472/66719885-d18d9c80-edf5-11e9-8e38-e4bca7458a96.png">

**Comment by sudara** [comment]
We could also do smaller illustrations here — the island has a lot of detail in it, so looks best at this size — but it's completely flexible.

**Comment by PhaseSevenComics** [comment]
> We mocked out how the forum could look. Seems like 96x96 is the display size there.

Cool, I'm going to get you high-res scans (600 dpi bitmap tifs) so that you can export a variety of sizes. I'll include 96 square, but you'll be able to get any needed screen resolution if that changes later on! Working on the first batch, which I'll upload tonight (MT)

**Comment by PhaseSevenComics** [comment]
I feel like the only spot that I'd want to use color is on the alonetone logo. It seems like if it was a bold flat color, like the orange, it would work in both light/dark mode. I'll understand if the orange is "verboten" though, since you said that was a key UX color (we don't want people like clicking on the illustrations...). Anyway, here's what that would look like:
![OrangeTest-Light](https://user-images.githubusercontent.com/54463667/66727806-b1aea680-edfe-11e9-81da-8e3348c97a94.jpg)
![OrangeTest-Dark](https://user-images.githubusercontent.com/54463667/66727812-b5dac400-edfe-11e9-8eb8-bdf8ca228d7e.jpg)
Does it look too much like a basketball???
