### ISSUE TITLE
Forum html metadata is missing, should show alonetone logo

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#798]
![Alonetone-a damn fine home for musicians 2019-09-29 20-50-48](https://user-images.githubusercontent.com/472/65837716-03353c80-e2fb-11e9-8aec-e0faabe1c8b3.jpg)

**Comment by fadib** [comment]
<img width="515" alt="Screen Shot 2019-10-12 at 12 15 26 AM" src="https://user-images.githubusercontent.com/89159/66694795-6de46180-ec85-11e9-900b-36d92ce3fef1.png">

It's not the alonetone logo but at least they grabbed an image now. We can use open graph markup here to show the alonetone logo inside forum HTML. I can work on this issue.

**Comment by sudara** [comment]
Ah interesting. Yeah, looks like it's our fault, as I believe we override the thredded forum layout with `thredded.html.erb`.

**Comment by sudara** [comment]
Maybe let's close this for now. Avatars are ok!
