### ISSUE TITLE
Waveforms not vertically aligned on single big player views

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#800]
Although they are for playlist views

<img width="362" alt="Screenshot 2019-09-30 12 56 27" src="https://user-images.githubusercontent.com/407724/65907580-d841fb80-e381-11e9-9ce7-95fdf000c100.png">
<img width="311" alt="Screenshot 2019-09-30 12 55 13" src="https://user-images.githubusercontent.com/407724/65907582-d8da9200-e381-11e9-868e-e79e2b61caef.png">

**Comment by sudara** [comment]
ANGRY!
