### ISSUE TITLE
What to do about the failed active storage sidekiq jobs?

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#814]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/472/65978385-e83a0800-e473-11e9-81fc-693565023332.png">

**Comment by Manfred** [comment]
Just delete them all.

**Comment by sudara** [comment]
Won’t new uploads create more of them?

**Comment by Manfred** [comment]
Yes, but I think they failed because of the way we migrated the S3 objects and not because something is inherently broken. These jobs should run just fine for new uploads.

**Comment by sudara** [comment]
Deleted the queues for now.

`active_storage_purge` –> when blob is deleted, ensures attachment is deleted from storage
`active_storage_analysis` –> not using it, identifies content type and reports dimensions for images — redownloads the file from storage 

<img width="1428" alt="Screen Shot 2019-10-02 at 15 42 58" src="https://user-images.githubusercontent.com/472/66049318-7d4c0800-e52b-11e9-9fb6-872f1d61e68f.png">

**Comment by sudara** [comment]
Let's turn off analysis :)
