### ISSUE TITLE
Local SVG issue on manfred's machine

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#816]
SVG state appears unhappy

<img width="363" alt="image" src="https://user-images.githubusercontent.com/472/65979125-10763680-e475-11e9-8e48-e2df5f652fa2.png">

**Comment by sudara** [comment]
@manfred can you let me know which browser version this is on?

**Comment by Manfred** [comment]
Safari 13.0.1 on macOS Mojave.

**Comment by Manfred** [comment]
Wasn't there something with the MorphSVG JS that we had to install by hand? Maybe I have the wrong version?

**Comment by sudara** [comment]
Good call! Sent you the updated...
