### ISSUE TITLE
Locally, ActiveStorage is checking presence of variants on s3

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#826]
Just wanted to document this, in case it's unintentional. 

I have `storage_service: s3` to use production alonetone s3 as the source, but it looks like it's doing HEAD requests to s3 to check for thumbnail existence. 

```
 ActiveStorage::Attachment Load (0.4ms)  SELECT `active_storage_attachments`.* FROM `active_storage_attachments` WHERE `active_storage_attachments`.`record_id` = 4008 AND `active_storage_attachments`.`record_type` = 'User' AND `active_storage_attachments`.`name` = 'avatar_image' LIMIT 1
  ↳ app/models/user.rb:254:in `avatar_image_location'
  ActiveStorage::Blob Load (0.3ms)  SELECT `active_storage_blobs`.* FROM `active_storage_blobs` WHERE `active_storage_blobs`.`id` = 4692 LIMIT 1
  ↳ app/models/image_variant.rb:30:in `to_active_storage_variant'
  S3 Storage (145.1ms) Checked if file exists at key: variants/l9vkcn6dqtuc1kjxg0jqbbsu6uhu/e8b691c06222c3c48e2d9eefb3d2b770d953630c9817422f75881eeb4525d19c (yes)
  S3 Storage (1.2ms) Generated URL for file at key: variants/l9vkcn6dqtuc1kjxg0jqbbsu6uhu/e8b691c06222c3c48e2d9eefb3d2b770d953630c9817422f75881eeb4525d19c (https://s3.amazonaws.com/stash.alonetone.com/variants/l9vkcn6dqtuc1kjxg0jqbbsu6uhu/e8b691c06222c3c48e2d9eefb3d2b770d953630c9817422f75881eeb4525d19c?response-content-disposition=inline%3B%20filename%3D%22Portrait.jpg%22%3B%20filename%2A%3DUTF-8%27%27Portrait.jpg&response-content-type=image%2Fjpeg&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1Q6FSC4S0DWWWG6ZJAR2%2F20191003%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191003T234614Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=0ca2ee409fb07e09adf981fc635d4e08f996ea86a33b7927ca28a36721b97af6)
```

**Comment by sudara** [comment]
I guess the surprise is mainly that each image on each load takes 150ms to load because of the extra check for presence.

I think what I'll do is remove the variants folder from s3. Maybe I can setup "faux fastly" in the future...

**Comment by Manfred** [comment]
Right, maybe I should have explained this.  If you want to use production dumps in development (which I still think you shouldn't) then you also want to run the fake Fastly implementation. In all other cases I would recommend using disk storage.

The default Active Storage representation controller does indeed perform HEAD requests (or File.exist? on disk) to check if the variant exists because it wants to check if it should create it. This also means that it will create the variants on S3 when you have the production bucket.

## Loading production dumps for debugging or testing

1. Configure S3 (preferably with a read-only IAM user)
2. Set up fake Fastly

```
# Procfile

web: bundle exec rails server --port 3000
fastly: PORT=6060 bundle exec bin/fastly
sidekiq: bundle exec sidekiq
```

```
# config/alonetone.yml

# The first path segment (process) will be ignored by
# the fake Fastly implementation to be compatible with
# the production configuration.
fastly_base_url: http://localhost:6060/process
```

## General local development

```
# Procfile

web: bundle exec rails server --port 3000
sidekiq: bundle exec sidekiq
```

```
# config/alonetone.yml

development:
  hostname: localhost:3000
  email: support@example.com
  storage_service: disk
```

**Comment by sudara** [comment]
Really appreciate this response, thank you!

This was mainly curiosity... My plan is to move to seeds and use `filesystem` — I think this will be better for expanding and improving seeds for things like css and layout edge cases.
