### ISSUE TITLE
rake db:reset fails with `unknown attribute 'password'`

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#833]
This only happened the first time I used it, but thought I'd mention. Prob some obscure authlogic thing.

```
➜  alonetone git:(master) bundle exec rake db:reset
Dropped database 'alonetone_seeds'
Dropped database 'alonetone_test'
Created database 'alonetone_seeds'
Created database 'alonetone_test'
rake aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'password' for User.
/Users/sudara/Sites/alonetone/db/seeds.rb:49:in `<top (required)>'
/Users/sudara/.rbenv/versions/2.6.1/bin/bundle:23:in `load'
/Users/sudara/.rbenv/versions/2.6.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:reset => db:setup => db:seed
(See full trace by running task with --trace)
➜  alonetone git:(master) bundle exec rake db:reset
Dropped database 'alonetone_seeds'
Dropped database 'alonetone_test'
Created database 'alonetone_seeds'
Created database 'alonetone_test'
You can now sign in with: admin - testing123
You can now sign in with: moderator - testing123
You can now sign in with: musician - testing123
You can now sign in with: marieh - testing123
You can now sign in with: carole - testing123
You can now sign in with: petere - testing123
```

**Comment by sudara** [comment]
Looks like this happens reliably on first time setups.

**Comment by Manfred** [comment]
Authlogic checks if the database is loaded when we call `acts_as_authentic` and does nothing if there is no database. Authlogic is never initialized because `db:setup` runs `db:create` and `db:seed` in the same process. The ‘solution’ would be unload and reload the `User` class at the start of the seeds.

**Comment by project-orcon** [comment]
> Authlogic checks if the database is loaded when we call `acts_as_authentic` and does nothing if there is no database. Authlogic is never initialized because `db:setup` runs `db:create` and `db:seed` in the same process. The ‘solution’ would be unload and reload the `User` class at the start of the seeds.

How would you do this - I've tried User.reset_column_information but I'm still getting the same error

**Comment by sudara** [comment]
@project-orcon See the PR that closes this issue: https://github.com/sudara/alonetone/pull/920/files
