### ISSUE TITLE
Move CI to Circle

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#836]
I've been happy, but lately we are seeing daily problems that are related to their infrastructure. I break CI enough without these being added into the mix, creating noise and delay.

Also it would be nice to run 5 concurrent builds ala circle/buildkite.

This is maybe not infrastructure, but apparently it's trying to run a branch that I just merged and then was deleted from github:
 
https://travis-ci.com/sudara/alonetone/builds/130981479

**Comment by Manfred** [comment]
Sure, do you want me to help you with that somehow?

**Comment by sudara** [comment]
Sure! This would be useful maybe after #793 

We keep seeing errors of many flavors, latest one here: https://travis-ci.com/sudara/alonetone/builds/131839631?utm_source=slack&utm_medium=notification 

I just don't know where it's most straightforward. Circle says we get to build 4 containers, not sure if that's by default or if I have to contact them. https://circleci.com/pricing/#faq-section-linux

**Comment by sudara** [comment]
I actually am not very well educated on what the options are. I guess Circle would give us slightly more parallel jobs and I'm moving https://github.com/sudara/stitches to it, so we could do that.

**Comment by sudara** [comment]
Wishlist:

1. Move to circle workflows 2.1 
2. Cache as much as possible / use orbs if it helps
3. Run feature tests in parallel to rest of suite

**Comment by Manfred** [comment]
Do you still want to switch to CircleCI or should I close this issue?

**Comment by sudara** [comment]
#1063 moved us to GitHub actions. Nice catch...
