### ISSUE TITLE
Improve DB seeds

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#837]
## Approach

* [ ] Create helpers to create users/tracks/playlists/listens/comments in batches, relying on faker to populate 
* [ ] Have the main seeds file stay high level, mainly configuring and calling helpers
* [ ] Have a seeds file named after each edge case user, so it's easy to see where to edit and modidfy

## General needs

* [ ] Users with long names and long single words within the name
* [ ] Tracks/Playlists with long names and long single words within the name
* [ ] Users should have various states of profile filled out (no pic / with pic / no bio / with bio / no social links / all the social links)
* [ ] Enough users where at least a couple hit pagination: http://localhost:3000/users/by/last_uploaded 
* [ ] Enough playlists where this fleshes out into a grid http://localhost:3000/playlists
* [ ] Playlists with Externals Links
* [ ] Comments of various length from guest and users, some marked as spam.
* [ ] Following relationships among users
* [ ] Track descriptions and Forum posts using all markdown
* [ ] **Forum Seeds** (see https://github.com/thredded/thredded/blob/master/lib/thredded/database_seeder.rb) 

## Specific edge cases 

* [ ] Track with lyrics, images, videos in them.
* [ ] Track with no recent listeners / 5 recent listeners / 50 recent listers 
* [ ] Track with 0 favorites / 5 favorites / 50 favorites
* [ ] Track with 0 comments / 5 comments / 50 comments
* [ ] Playlist with 0 tracks and private / 10 tracks / 50 tracks
* [ ] User with 0 tracks / 5 tracks / 50 tracks / 500 tracks
* [ ] User with 0 comments / 5 comments / 50 comments
* [ ] User who has deleted some of their tracks (which also have comments and listens)

Still open questions

* [ ] Images.... Will we need a batch of 100 or something to play with?

~Open~ Old questions:
<details>
1) seeds.rb is already 300 lines and takes a while to parse — how maintainable is it to keep using 1 file? What options do we have to introduce a bit of structure there?

2) Is there a route we could take that would be less brittle? I'm imagining adding tables and relations down the line and having to comb through the seeds file and make sure each user has a value for a new col / relation. 

3) From a UI standpoint, the best way to make seeds is to evaluate the needs from the UI point of view and strategically add them, as we dev, on a case by case basis. It would therefore be best if we could devise a straightforward way to open this up so @ofsound would feel comfy adding new records, knowing they will persist. 

4) Would a reasonable option be to commit a sqlite db and have a rake task that then takes your version and overwrites the repo's version?

5) Regarding structure of the data: Manfred suggested having "one weird user with all the edge cases" — I think we could go a bit further and have multiple personas that represent different edge cases we see. For example "heavy user" would have 30 playlists and 400 tracks and 400 comments.  "Lurker" would have only made 3 comments but never uploaded anything. 

6) We also need to generate decent admin data, which means we need to have a full suite of deleted tracks.

@ofsound As someone who has curated your own db, can you think of some requirements / must-haves that you've setup locally?
</details>

**Comment by Manfred** [comment]
> 1] how maintainable is it to keep using 1 file

Writing and maintaining development and test data takes time but is always worth it in my opinion. You might run into merge issues when using one file, but I feel that's mostly a problem for large teams that have multiple developers working on the data model.

> 2] Is there a route we could take that would be less brittle?

You make sure you have good validation on your models and use code similar to the controllers to create the data. Also; we can run `rails db:seed` on CI to make sure it doesn't break unnoticed.

> 3] Would a reasonable option be to commit a sqlite db

Not really, a sqlite DB doesn't diff very well in Git. You could do it outside of the repository somehow. For example, through Dropbox or some other document hosting service.

> 5] Manfred suggested having "one weird user with all the edge cases" — I think we could go a bit further

Yes, I meant multiple users so you can switch between test scenarios easily.

> 6] we need to have a full suite of deleted tracks.

Yes.

---

I don't mind adding seeds if someone creates a ticket or asks on Slack. We could even do it based on a database dump.

**Comment by sudara** [comment]
Thanks Manfred! 

With the main goal in mind to incentivize / make it trivial to add edge cases to the seeds vs. keep specialized individual dev databases that we feel "precious" about, it seems like the viable options are:  

## Double down on making seeds.rb fleshed out and friendly

Break into multiple files, have a helper file with a few more utilities to make things less verbose. 

1 file per "edge case user" might be a good mental model, though we'll probably want to populate at least a couple dozen users so we can properly fill out certain sections of the UI

## Manually pass around a dump derived from seeds

This seems high friction / atomic enough where it doesn't reliably solve things, especially with diverging dev databases.

## Commit some sort of proxy dump to the repo

Since we're only 4 people, this seems overkill.

Some general needs:

* [ ] Users should have various states of profile filled out (no pic / with pic / no bio / with bio)
* [ ] Enough users where at least a couple hit pagination: http://localhost:3000/users/by/last_uploaded 
* [ ] Enough playlists where this fleshes out into a grid http://localhost:3000/playlists
* [ ] Comments of various length from guest and users, some marked as spam.

Specific edge cases we need: 

* [ ] Track with no recent listeners / 5 recent listeners / 50 recent listers 
* [ ] Track with 0 favorites / 5 favorites / 50 favorites
* [ ] Track with 0 comments / 5 comments / 50 comments
* [ ] Playlist with 0 tracks and private / 10 tracks / 50 tracks
* [ ] User with 0 tracks / 5 tracks / 500 tracks
* [ ] User who has deleted some of their tracks (which also have comments and listens)

Two other questions:

1. Wondering if we should name a couple of the edge case users semantically ('talkative musician', 'prolific monster', 'mr. popular', 'lurker') to help target them during dev.

2. Wondering if the rest of the bulk data could be handled by Faker.

**Comment by sudara** [comment]
@ofsound Any other edge cases or specific needs on your end you can think of? Imagining resetting the database — what would be annoying to build back up vs. what you have now?

**Comment by sudara** [comment]
> we can run rails db:seed on CI to make sure it doesn't break unnoticed. 

Love this idea.

**Comment by ofsound** [comment]
I haven't done much with my local database as the user content in there is pretty varied.

The edge cases that have confused frontend in the past have been not having a mix of SVG and JPG for users and album covers.

And also, finding very long album titles, users and descriptions on the site that exceeded what I'd seen locally.

Including stringslikethisbecausesomeartistdon'twanttoconformtoconventions

**Comment by sudara** [comment]
> stringslikethisbecausesomeartistsdon'twanttoconformtoconventions

heh, sounds good!

> as the user content in there is pretty varied.

Just to be clear, as I keep forgetting — are you using an old dump from back in the day? Or is the database just stuff you've collected and added over time? If the latter, maybe we can screenshare and take a look at it to see if we can tease out any additional requirements.

**Comment by sudara** [comment]
Updated the issue to have our combined generic / specific data needs in the description.

In person, we decided to 

1. create a few helpers to create users/tracks/playlists in batches, relying on faker to populate 
2. have the main seeds file stay high level, mainly configuring and calling helpers
3. have an edge cases seeds file and/or a seeds file per edge case
