### ISSUE TITLE
"Gift instead of Punishment" illustrations

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#842]
I think we want to do 3-4 of these:

* No search results: "We couldn't find any search results for ABC XYZ!"
* 404 not found: "Hmm, that doesn't seem to exist" (could reuse the same illustration as above if you like, or variation)
* 500 error: "Yikes! An error! We've been notified"
* Down for maintenance (aka fail whale, see https://www.theatlantic.com/technology/archive/2015/01/the-story-behind-twitters-fail-whale/384313/ )

Regarding sizes, I'm thinking we should consider an rough area 320px by 400px to be the area that will display on all devices, including the smallest phones (which range 320-500ish wide). Any message/text/important stuff would happen in those windows.

Optionally we can fit "more" of an illustration onto mobile by shrinking the size down, maybe even just a bit. 

Do we want to use browser text here too vs. drawn?

<img width="1248" alt="8*) * 2019-10-09 19-48-11" src="https://user-images.githubusercontent.com/472/66506875-6fb7f480-eace-11e9-9619-d3ddecda4485.png">

One idea I had if you don't want to draw a mega 1500x1300 rectangle would be to actually have two illustrations, a "footer" and main illustration, like so:

<img width="1248" alt="8*) * 2019-10-09 19-48-11" src="https://user-images.githubusercontent.com/472/66507282-32a03200-eacf-11e9-87c2-af1a80432e07.png">

**Comment by sudara** [comment]
@phasesevencomics Whups, meant to tag you on this.

**Comment by PhaseSevenComics** [comment]
This is rad, thanks so much for all the pixel dimensions and everything. I'll get to brainstorming on these....

**Comment by PhaseSevenComics** [comment]
These are all done!

**Comment by sudara** [comment]
Amazing work, thank you Alec!!!
