### ISSUE TITLE
Investigate strange SVG rendering on iPad

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#880]
![1236 PM](https://user-images.githubusercontent.com/407724/67707194-ac656600-f97f-11e9-8a53-bb035a0d9720.jpeg)

**Comment by sudara** [comment]
Weird! Just FYI these might be deprecated via #791 — we didn't get to them yesterday, but we will probably go icon + label for them.

**Comment by sudara** [comment]
Is this still a problem with the new versions of these buttons?

**Comment by ofsound** [comment]
The new ones display perfect on iPad. 

I think it was a line join or 'miter' something or another issue from SVG exporting/encoding?

**Comment by sudara** [comment]
🍾
