### ISSUE TITLE
Mass Edit ( via playlist > edit descriptions ) has no navigation back to playlist

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#881]
Could seem like a dead end to a less savvy user.

<img width="549" alt="Screenshot 2019-10-28 12 45 57" src="https://user-images.githubusercontent.com/407724/67707879-e97e2800-f980-11e9-8bba-1bae9817eb9e.png">

**Comment by sudara** [comment]
We removed getting to mass_edit from a playlist, so closing this out for now.
