### ISSUE TITLE
Refactor add_track/remove_track

### ISSUE THREAD

**Issue by innatewonderer** [sudara/alonetone#894]
[From Sudara](https://github.com/sudara/alonetone/pull/878#discussion_r343325189):
```
+1 to removing the model callback though! We can do that in add_track/remove_track (which ideally get moved into a new tracks_controller as create/destroy as those actions haven't been updated since REST was a thing!!).
```

**Comment by innatewonderer** [comment]
@sudara, thoughts, considering that currently all of our `tracks'` behavior is handled through `assets_controller` per routes:
```
    resources 'tracks', controller: :assets do
      member do
        get :share
        get :stats
      end
      collection do
        get  :latest
        post :search
        get  :mass_edit
      end
      resources :comments,  only: [:create, :destroy]
    end
```
should we move all actions that make sense to new tracks_controller or come up with another way?

**Comment by sudara** [comment]
Correct me if I'm wrong, but I think what you are asking is "we already have a `tracks` route, representing everything that happens on an `asset` under the hood. Wouldn't a `tracks_controller` conflict with that?"

Let's continue this discussion in your other issue #882 and close this one out. You can see [my comment](https://github.com/sudara/alonetone/issues/882#issuecomment-547917493) for suggested controller tweaks.
