### ISSUE TITLE
filename delegated to attachment, but attachment is nil

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#916]
## Error in alonetone

**ActionView::Template::Error** in **assets#show**
filename delegated to attachment, but attachment is nil

[View on Bugsnag](https://app.bugsnag.com/alonetone/alonetone/errors/5dcc37c11ef06d0019f435ed?event_id=5dcc59fb005331eaa0750000&i=gh&m=ci)

## Stacktrace

    app/views/shared/_asset.html.erb:29 - _app_views_shared__asset_html_erb___3028549533620303048_70233455473200
    app/views/assets/show.html.erb:1 - _app_views_assets_show_html_erb___1552870722523836647_70233455397720

[View full stacktrace](https://app.bugsnag.com/alonetone/alonetone/errors/5dcc37c11ef06d0019f435ed?event_id=5dcc59fb005331eaa0750000&i=gh&m=ci)

*Created by Jenya Zueva via Bugsnag*

**Comment by Manfred** [comment]
Maybe we should investigate Asset records without an `audio_file`. Can we run `bin/verify-storage` at some point to get an idea how many records are currently broken?

**Comment by sudara** [comment]
``` 
deploy@wurli:/data/alonetone$ RAILS_ENV=production bundle exec bin/verify-storage
bundler: failed to load command: bin/verify-storage (bin/verify-storage)
NameError: uninitialized constant Greenfield
  bin/verify-storage:113:in `<top (required)>'
deploy@wurli:/data/alonetone$ RAILS_ENV=production bin/verify-storage
Traceback (most recent call last):
bin/verify-storage:113:in `<main>': uninitialized constant Greenfield (NameError)
```

Looks like I didn't remove greenfield support from that bin file, but I can do that.

**Comment by Manfred** [comment]
By the way, not all these delegate errors will have the same cause. The ‘issue’ is that the record returns a kind of proxy object. For example: `playlist.cover_image` will always return the proxy object irregardless of whether is has a cover image associated. You have to query `playlist.cover_image.attached?` to find out if it's there. A lot of methods are delegated from the attachment proxy so they will cause the exception unless you check first.

**Comment by sudara** [comment]
The last time I saw this on production it felt like I triggered manually it
by landing on assets#show of a track with no waveform, making multiple
requests (and therefore mutilple jobs). Could have been a coincidence. I
had just restarted sidekiq, which had been stopped but not reaped, which
made me think it could have been rave condition-y with waveforms.

**Comment by sudara** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionView::Template::Error** in **playlists#show**](https://app.bugsnag.com/alonetone/alonetone/errors/5dcc37c11ef06d0019f435ed?event_id=5ddc6f9f00532e0ca3e00000&i=gh&m=ra)
