### ISSUE TITLE
playlists#all undefined method `login' for nil:NilClass

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#917]
## Error in alonetone

**ActionView::Template::Error** in **playlists#all**
undefined method `login' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/alonetone/alonetone/errors/5dcc5660165aff001920166f?event_id=5dcc5b1000532f2b93be0000&i=gh&m=ci)

## Stacktrace

    app/views/shared/_playlist.html.erb:2 - block in _app_views_shared__playlist_html_erb___3922616358317901537_47406148536800
    app/helpers/record_tag_helper.rb:99 - content_tag_for_single_record
    app/helpers/record_tag_helper.rb:85 - block in content_tag_for
    app/helpers/record_tag_helper.rb:84 - map
    app/helpers/record_tag_helper.rb:84 - content_tag_for
    app/views/shared/_playlist.html.erb:1 - _app_views_shared__playlist_html_erb___3922616358317901537_47406148536800
    app/views/playlists/all.html.erb:5 - _app_views_playlists_all_html_erb___1055281111046210064_70233471646220

[View full stacktrace](https://app.bugsnag.com/alonetone/alonetone/errors/5dcc5660165aff001920166f?event_id=5dcc5b1000532f2b93be0000&i=gh&m=ci)

*Created by Jenya Zueva via Bugsnag*

**Comment by innatewonderer** [comment]
Fixed in here 
https://github.com/sudara/alonetone/commit/94069abbcb7b891f442877ff25575cd7fa14ac05

**Comment by sudara** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionView::Template::Error** in **playlists#all**](https://app.bugsnag.com/alonetone/alonetone/errors/5dcc5660165aff001920166f?event_id=5dd0ad940053324faaf40000&i=gh&m=ra)

**Comment by sudara** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActionView::Template::Error** in **playlists#all**](https://app.bugsnag.com/alonetone/alonetone/errors/5dcc5660165aff001920166f?event_id=5dd940000053257cb3060000&i=gh&m=ra)
