### ISSUE TITLE
Titles with pipe character break permalink creation

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#924]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/472/68875225-bff42900-0702-11ea-8012-2baa7e076924.png">

These titles translate into unusable permalinks which 404 

https://alonetone.com/joeoctave2/tracks/afo-kedi-%7C%7C-crudemusik.com

**Comment by Manfred** [comment]
Is it possible these permalinks were changes by the migration without expiring the cache? In other words, did you flush memcached on the server?

**Comment by Manfred** [comment]
Ah, the problem is the dot in the permalink and not the pipes. Rails routing thinks it's a format.

**Comment by Manfred** [comment]
I tried to change the constraints for the request path segment but that broke the MP3 URL because that actually uses the dot to include the format. Instead I decided to disallow dots from the permalink. PR incoming in 3… 2… 1….
