### ISSUE TITLE
Implement "Get An Account" page

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#929]
As seen in figma here: https://www.figma.com/file/YdjrVsNumbBsWVo82Wje2h6N/alonetone-white-theme?node-id=1361%3A7177

<img width="751" alt="image" src="https://user-images.githubusercontent.com/472/68903234-c69e9280-073a-11ea-8098-9338efc60a1a.png">

Note: the dark theme illustration will be white on black, figma just can't invert images...

Needs:

* [ ] White and Dark theme versions of new form fields (these are officially componentized now, so we might want to define these and see how it affects the other forms on the site, such as create new playlist
* [ ] Define the blank slate with illustration. We will have a "wash" for the background of the blank slate this coming sunday. We want to use alec for this page and the text that is there already. Here are the raw contributor illustrations: https://www.dropbox.com/s/4iea701dz6rxpml/alonetone_peeps.zip?dl=0
* [ ] The "checkboxes as radio buttons" pattern for the patreon support going to need some love. I think we actually want to use radio buttons behind the scenes here and style them to look like checkboxes, if that makes sense. 
* [ ] The "What's your gig" section is multi select checkboxes

**Comment by Manfred** [comment]
Is there a design reason for using a checkbox as a radio button?

**Comment by sudara** [comment]
I'm not 100% sure, but either @smoofles thinks 🔘 are the devil or it could be that we just haven't gotten around to designing a 🔘 component yet.

**Comment by smoofles** [comment]
Video checkbox killed the radio star! 
 
Haven’t gotten around to it yet, will do next thing. 👍
