### ISSUE TITLE
Illustration Wrap Up

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#957]
Now that contributor images and most of the "reward vs. punishment" big images are done, we are down to the small stuff! 

Sudara 

* [x] Export other illustrations to correctly sized png 
* [x] Determine whether or not we need to redraw or color the IslandUke image re: expected size on home page (Sudara task)
* [x] Determine what other "about" illustrations are needed

Alec 

* [x] Down for maintenance "reward vs. punishment" page
* [x] Remaining forum images 1) "Gear Talk" and 2) "Making Music" which is sort of a general music process/chat. I think we will use "MicChords" gnome for 1) and "Vinyl" or "harmonica" gnome for 2). Could also use announcement gnome for 2)
* [x] Deliver TIFF version of IslandUke, optionally with any changes (color accents?)
* [x] "Privacy" gnome. Could just be a sheet of legal paper gnome?
* [x] "Help!" gnome. Could be panic or being calmed. 
* [x] Rework 'fly-swatter' gnome or give approval on sudara's altered square version.
* [x] Deliver TIFF of missing gnomes that we know and love, specifically alonetone-headded gnome, tuning fork gnome, harmonica gnome (might want to use this one on the forum)
* [x] Optional: more "smoke" on the 500 page so it goes offscreen and/or fades out...See screenshot https://github.com/sudara/alonetone/pull/950#issuecomment-564782453

## Scheduling dem gnomes

* About https://alonetone.com/about
  * [x] Open source Gnome
  * [x] Free / Always free gnomes
* Help https://alonetone.com/about/help
  * [x] Panicing Gnome?
* Privacy
  * [x] Privacy Gnome
* Why I built alonetone https://alonetone.com/about/why-i-built-alonetone
  * [x] Introduce 
  * [ ] Demo vs. release? (Could use Vinyl gnome)

/cc @PhaseSevenComics

**Comment by sudara** [comment]
I think the island Uke will work if we can keep it this size, checking with @smoofles if he has opinionz

<img width="718" alt="image" src="https://user-images.githubusercontent.com/472/70644348-20638100-1c43-11ea-8a4c-54dad6974dba.png">

**Comment by PhaseSevenComics** [comment]
Wait! I gotta redraw the alonetone logo for the sun. Gotta represent that smooth new whole note! I can update it in any of the spots that also use it (on a few gnome heads, I think?)

**Comment by PhaseSevenComics** [comment]
> Alec
> 
> * [ ]  Down for maintenance "reward vs. punishment" page
> * [ ]  Remaining forum images 1) "Gear Talk" and 2) "Making Music" which is sort of a general music process/chat. We could use "MicChords" gnome for 1) and "Vinyl" gnome for 2). Could also use announcement gnome for 2)
> * [ ]  "Privacy" gnome. Could just be a sheet of legal paper gnome?
> * [ ]  "Help!" gnome. Could be panic or being calmed.

Thanks so much for this list! I'll try to have everything wrapped up by the end of this weekend.

**Comment by sudara** [comment]
> Gotta represent that smooth new whole note! I can update it in any of the spots that also use it 

Ack, sorry for misrepresenting in the mockup — the old logo is still used on the white theme, and we plan to keep it that way. New smooth/flat whole note is used only on dark theme.

I thought color might be nice on the island image? Though not 100% sure that would make sense on the dark theme...

<img width="708" alt="image" src="https://user-images.githubusercontent.com/472/70646078-7e459800-1c46-11ea-8b29-1578bfff1475.png">

<img width="673" alt="image" src="https://user-images.githubusercontent.com/472/70646099-8271b580-1c46-11ea-971e-1038336fa716.png">

**Comment by PhaseSevenComics** [comment]
Oh, okay! Yeah, I like the idea of color for this one (subtle, just a few shades). Maybe send me high-res versions of both logos so I can fold them into the design?

**Comment by sudara** [comment]
@PhaseSevenComics 

Sounds good!

Light: https://alonetone.com/images/alonetone-logo-2000px-square.png
Dark: https://github.com/sudara/alonetone/files/3952603/alonetone_logo_dark.svg.zip

With the design above, light theme background for this area is #E6E8E8 and dark theme is #1D1B1B

**Comment by sudara** [comment]
Got a question on one of the forum images. I'd love to use fly-swatter gnome, but we'd need it to be square.

![AT_Forum_Bug2](https://user-images.githubusercontent.com/472/70664414-a6df8900-1c6a-11ea-8f1a-db6b46e16d31.jpg)

This might work, but if you have any ideas on how to redraw as a square, lemme know! I like the idea of the forum being 100% gnomey. :D

![bug-light](https://user-images.githubusercontent.com/472/70664724-3e44dc00-1c6b-11ea-9afc-e77065ca3664.png)

**Comment by sudara** [comment]
Looks like it might also be nice to get TIFF versions of harmonica/alonetone-headded/tuning fork gnomes! 

I updated the todo lists :)

**Comment by sudara** [comment]
Oh, and while I'm pummeling you with email notifications: 

We were randomly wondering if you have any experience exporting this kind of illustration as svg. Seems like the gnomes would be a good candidate for vector export, which would make them very lightweight and easy to toggle color via css. But maybe it just *looks* like that would translate to svg easily, but in reality because the lines are all hand drawn, it would be a complex large file....? No stress on this, mainly curiosity since we've worked a lot with svg recently.

**Comment by sudara** [comment]
Woo!!!!
