### ISSUE TITLE
register_listen behavior for greenfield

### ISSUE THREAD

**Issue by wioux** [sudara/alonetone#97]

**Comment by sudara** [comment]
Do you remember what this issue was about? Otherwise I'll close it.

**Comment by wioux** [comment]
We don't create a listen when a track is played through listenapp. I don't quite remember why but I think because of pre-fetching it would have been wrong to create a listen when the asset is downloaded? This issue is just to figure out what to do.

**Comment by sudara** [comment]
OOOOOOOOH. Prefetching was the problem! Thanks!
