### ISSUE TITLE
Forum posts have waves of mis-attribution and duplicate content

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#989]
At least on Gear Talk, I've noticed this come and go, and appear as different permutations of incorrect data.

<img width="804" alt="Screen Shot 2020-02-12 at 4 22 29 PM" src="https://user-images.githubusercontent.com/407724/74386705-dff3c100-4db3-11ea-9bbe-0727b9e725c5.png">

**Comment by sudara** [comment]
Thanks for pointing it out. Looks like #780 should have been reopened, so I'm going to do that and close this out.
